# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::AddSeriesOptions < Sonarr::Model
  @[JSON::Field(key: "ignoreEpisodesWithFiles")]
  property ignore_episodes_with_files : Bool?

  @[JSON::Field(key: "ignoreEpisodesWithoutFiles")]
  property ignore_episodes_without_files : Bool?

  @[JSON::Field(key: "monitor")]
  property monitor : Sonarr::MonitorTypes?

  @[JSON::Field(key: "searchForMissingEpisodes")]
  property search_for_missing_episodes : Bool?

  @[JSON::Field(key: "searchForCutoffUnmetEpisodes")]
  property search_for_cutoff_unmet_episodes : Bool?
end
