# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::AlternateTitleResource < Sonarr::Model
  @[JSON::Field(key: "title", emit_null: true)]
  property title : String?

  @[JSON::Field(key: "seasonNumber", emit_null: true)]
  property season_number : Int32?

  @[JSON::Field(key: "sceneSeasonNumber", emit_null: true)]
  property scene_season_number : Int32?

  @[JSON::Field(key: "sceneOrigin", emit_null: true)]
  property scene_origin : String?

  @[JSON::Field(key: "comment", emit_null: true)]
  property comment : String?
end
