# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::AutoTaggingResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "name", emit_null: true)]
  property name : String?

  @[JSON::Field(key: "removeTagsAutomatically", emit_null: true)]
  property remove_tags_automatically : Bool?

  @[JSON::Field(key: "tags", emit_null: true)]
  property tags = [] of Int32

  @[JSON::Field(key: "specifications", emit_null: true)]
  property specifications = [] of Sonarr::Model::AutoTaggingSpecificationSchema
end
