# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::BackupResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "name", emit_null: true)]
  property name : String?

  @[JSON::Field(key: "path", emit_null: true)]
  property path : String?

  @[JSON::Field(key: "type", emit_null: true)]
  property type_field : Sonarr::BackupType?

  @[JSON::Field(key: "size", emit_null: true)]
  property size : Int64?

  @[JSON::Field(key: "time", emit_null: true, converter: Sonarr::TimeConverter)]
  property time : Time?
end
