# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::BlocklistResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "seriesId")]
  property series_id : Int32?

  @[JSON::Field(key: "episodeIds")]
  property episode_ids = [] of Int32

  @[JSON::Field(key: "sourceTitle")]
  property source_title : String?

  @[JSON::Field(key: "languages")]
  property languages = [] of Sonarr::Model::Language

  @[JSON::Field(key: "quality")]
  property quality : Sonarr::Model::QualityModel?

  @[JSON::Field(key: "customFormats")]
  property custom_formats = [] of Sonarr::Model::CustomFormatResource

  @[JSON::Field(key: "date", converter: Sonarr::TimeConverter)]
  property date : Time?

  @[JSON::Field(key: "protocol")]
  property protocol : Sonarr::DownloadProtocol?

  @[JSON::Field(key: "indexer")]
  property indexer : String?

  @[JSON::Field(key: "message")]
  property message : String?

  @[JSON::Field(key: "series")]
  property series : Sonarr::Model::SeriesResource?
end
