# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::BlocklistResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "seriesId", emit_null: true)]
  property series_id : Int32?

  @[JSON::Field(key: "episodeIds", emit_null: true)]
  property episode_ids = [] of Int32

  @[JSON::Field(key: "sourceTitle", emit_null: true)]
  property source_title : String?

  @[JSON::Field(key: "languages", emit_null: true)]
  property languages = [] of Sonarr::Model::Language

  @[JSON::Field(key: "quality", emit_null: true)]
  property quality : Sonarr::Model::QualityModel?

  @[JSON::Field(key: "customFormats", emit_null: true)]
  property custom_formats = [] of Sonarr::Model::CustomFormatResource

  @[JSON::Field(key: "date", emit_null: true, converter: Sonarr::TimeConverter)]
  property date : Time?

  @[JSON::Field(key: "protocol", emit_null: true)]
  property protocol : Sonarr::DownloadProtocol?

  @[JSON::Field(key: "indexer", emit_null: true)]
  property indexer : String?

  @[JSON::Field(key: "message", emit_null: true)]
  property message : String?

  @[JSON::Field(key: "series", emit_null: true)]
  property series : Sonarr::Model::SeriesResource?
end
