# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::CommandResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "name", emit_null: true)]
  property name : String?

  @[JSON::Field(key: "commandName", emit_null: true)]
  property command_name : String?

  @[JSON::Field(key: "message", emit_null: true)]
  property message : String?

  @[JSON::Field(key: "body", emit_null: true)]
  property body : Sonarr::Model::Command?

  @[JSON::Field(key: "priority", emit_null: true)]
  property priority : Sonarr::CommandPriority?

  @[JSON::Field(key: "status", emit_null: true)]
  property status : Sonarr::CommandStatus?

  @[JSON::Field(key: "result", emit_null: true)]
  property result : Sonarr::CommandResult?

  @[JSON::Field(key: "queued", emit_null: true, converter: Sonarr::TimeConverter)]
  property queued : Time?

  @[JSON::Field(key: "started", emit_null: true, converter: Sonarr::TimeConverter)]
  property started : Time?

  @[JSON::Field(key: "ended", emit_null: true, converter: Sonarr::TimeConverter)]
  property ended : Time?

  @[JSON::Field(key: "duration", emit_null: true)]
  property duration : String?

  @[JSON::Field(key: "exception", emit_null: true)]
  property exception : String?

  @[JSON::Field(key: "trigger", emit_null: true)]
  property trigger : Sonarr::CommandTrigger?

  @[JSON::Field(key: "clientUserAgent", emit_null: true)]
  property client_user_agent : String?

  @[JSON::Field(key: "stateChangeTime", emit_null: true, converter: Sonarr::TimeConverter)]
  property state_change_time : Time?

  @[JSON::Field(key: "sendUpdatesToClient", emit_null: true)]
  property send_updates_to_client : Bool?

  @[JSON::Field(key: "updateScheduledTask", emit_null: true)]
  property update_scheduled_task : Bool?

  @[JSON::Field(key: "lastExecutionTime", emit_null: true, converter: Sonarr::TimeConverter)]
  property last_execution_time : Time?
end
