# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::CustomFormatSpecificationSchema < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "implementation")]
  property implementation : String?

  @[JSON::Field(key: "implementationName")]
  property implementation_name : String?

  @[JSON::Field(key: "infoLink")]
  property info_link : String?

  @[JSON::Field(key: "negate")]
  property negate : Bool?

  @[JSON::Field(key: "required")]
  property required : Bool?

  @[JSON::Field(key: "fields")]
  property fields = [] of Sonarr::Model::Field

  @[JSON::Field(key: "presets")]
  property presets = [] of Sonarr::Model::CustomFormatSpecificationSchema
end
