# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::CustomFormatResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "includeCustomFormatWhenRenaming")]
  property include_custom_format_when_renaming : Bool?

  @[JSON::Field(key: "specifications")]
  property specifications = [] of Sonarr::Model::CustomFormatSpecificationSchema
end
