# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::CustomFormatResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "name", emit_null: true)]
  property name : String?

  @[JSON::Field(key: "includeCustomFormatWhenRenaming", emit_null: true)]
  property include_custom_format_when_renaming : Bool?

  @[JSON::Field(key: "specifications", emit_null: true)]
  property specifications = [] of Sonarr::Model::CustomFormatSpecificationSchema
end
