# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::CustomFilterResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "type", emit_null: true)]
  property type_field : String?

  @[JSON::Field(key: "label", emit_null: true)]
  property label : String?

  @[JSON::Field(key: "filters", emit_null: true)]
  property filters = [] of Hash(String, JSON::Any)
end
