# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::CustomFormatSpecificationSchema < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "name", emit_null: true)]
  property name : String?

  @[JSON::Field(key: "implementation", emit_null: true)]
  property implementation : String?

  @[JSON::Field(key: "implementationName", emit_null: true)]
  property implementation_name : String?

  @[JSON::Field(key: "infoLink", emit_null: true)]
  property info_link : String?

  @[JSON::Field(key: "negate", emit_null: true)]
  property negate : Bool?

  @[JSON::Field(key: "required", emit_null: true)]
  property required : Bool?

  @[JSON::Field(key: "fields", emit_null: true)]
  property fields = [] of Sonarr::Model::Field

  @[JSON::Field(key: "presets", emit_null: true)]
  property presets = [] of Sonarr::Model::CustomFormatSpecificationSchema
end
