# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::DelayProfileResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "enableUsenet", emit_null: true)]
  property enable_usenet : Bool?

  @[JSON::Field(key: "enableTorrent", emit_null: true)]
  property enable_torrent : Bool?

  @[JSON::Field(key: "preferredProtocol", emit_null: true)]
  property preferred_protocol : Sonarr::DownloadProtocol?

  @[JSON::Field(key: "usenetDelay", emit_null: true)]
  property usenet_delay : Int32?

  @[JSON::Field(key: "torrentDelay", emit_null: true)]
  property torrent_delay : Int32?

  @[JSON::Field(key: "bypassIfHighestQuality", emit_null: true)]
  property bypass_if_highest_quality : Bool?

  @[JSON::Field(key: "bypassIfAboveCustomFormatScore", emit_null: true)]
  property bypass_if_above_custom_format_score : Bool?

  @[JSON::Field(key: "minimumCustomFormatScore", emit_null: true)]
  property minimum_custom_format_score : Int32?

  @[JSON::Field(key: "order", emit_null: true)]
  property order : Int32?

  @[JSON::Field(key: "tags", emit_null: true)]
  property tags = [] of Int32
end
