# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::DownloadClientBulkResource < Sonarr::Model
  @[JSON::Field(key: "ids", emit_null: true)]
  property ids = [] of Int32

  @[JSON::Field(key: "tags", emit_null: true)]
  property tags = [] of Int32

  @[JSON::Field(key: "applyTags", emit_null: true)]
  property apply_tags : Sonarr::ApplyTags?

  @[JSON::Field(key: "enable", emit_null: true)]
  property enable : Bool?

  @[JSON::Field(key: "priority", emit_null: true)]
  property priority : Int32?

  @[JSON::Field(key: "removeCompletedDownloads", emit_null: true)]
  property remove_completed_downloads : Bool?

  @[JSON::Field(key: "removeFailedDownloads", emit_null: true)]
  property remove_failed_downloads : Bool?
end
