# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::DownloadClientConfigResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "downloadClientWorkingFolders", emit_null: true)]
  property download_client_working_folders : String?

  @[JSON::Field(key: "enableCompletedDownloadHandling", emit_null: true)]
  property enable_completed_download_handling : Bool?

  @[JSON::Field(key: "autoRedownloadFailed", emit_null: true)]
  property auto_redownload_failed : Bool?

  @[JSON::Field(key: "autoRedownloadFailedFromInteractiveSearch", emit_null: true)]
  property auto_redownload_failed_from_interactive_search : Bool?
end
