# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::EpisodeFileResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "seriesId")]
  property series_id : Int32?

  @[JSON::Field(key: "seasonNumber")]
  property season_number : Int32?

  @[JSON::Field(key: "relativePath")]
  property relative_path : String?

  @[JSON::Field(key: "path")]
  property path : String?

  @[JSON::Field(key: "size")]
  property size : Int64?

  @[JSON::Field(key: "dateAdded", converter: Sonarr::TimeConverter)]
  property date_added : Time?

  @[JSON::Field(key: "sceneName")]
  property scene_name : String?

  @[JSON::Field(key: "releaseGroup")]
  property release_group : String?

  @[JSON::Field(key: "languages")]
  property languages = [] of Sonarr::Model::Language

  @[JSON::Field(key: "quality")]
  property quality : Sonarr::Model::QualityModel?

  @[JSON::Field(key: "customFormats")]
  property custom_formats = [] of Sonarr::Model::CustomFormatResource

  @[JSON::Field(key: "customFormatScore")]
  property custom_format_score : Int32?

  @[JSON::Field(key: "indexerFlags")]
  property indexer_flags : Int32?

  @[JSON::Field(key: "releaseType")]
  property release_type : Sonarr::ReleaseType?

  @[JSON::Field(key: "mediaInfo")]
  property media_info : Sonarr::Model::MediaInfoResource?

  @[JSON::Field(key: "qualityCutoffNotMet")]
  property quality_cutoff_not_met : Bool?
end
