# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::EpisodesMonitoredResource < Sonarr::Model
  @[JSON::Field(key: "episodeIds", emit_null: true)]
  property episode_ids = [] of Int32

  @[JSON::Field(key: "monitored", emit_null: true)]
  property monitored : Bool?
end
