# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::EpisodeResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "seriesId", emit_null: true)]
  property series_id : Int32?

  @[JSON::Field(key: "tvdbId", emit_null: true)]
  property tvdb_id : Int32?

  @[JSON::Field(key: "episodeFileId", emit_null: true)]
  property episode_file_id : Int32?

  @[JSON::Field(key: "seasonNumber", emit_null: true)]
  property season_number : Int32?

  @[JSON::Field(key: "episodeNumber", emit_null: true)]
  property episode_number : Int32?

  @[JSON::Field(key: "title", emit_null: true)]
  property title : String?

  @[JSON::Field(key: "airDate", emit_null: true)]
  property air_date : String?

  @[JSON::Field(key: "airDateUtc", emit_null: true, converter: Sonarr::TimeConverter)]
  property air_date_utc : Time?

  @[JSON::Field(key: "lastSearchTime", emit_null: true, converter: Sonarr::TimeConverter)]
  property last_search_time : Time?

  @[JSON::Field(key: "runtime", emit_null: true)]
  property runtime : Int32?

  @[JSON::Field(key: "finaleType", emit_null: true)]
  property finale_type : String?

  @[JSON::Field(key: "overview", emit_null: true)]
  property overview : String?

  @[JSON::Field(key: "episodeFile", emit_null: true)]
  property episode_file : Sonarr::Model::EpisodeFileResource?

  @[JSON::Field(key: "hasFile", emit_null: true)]
  property has_file : Bool?

  @[JSON::Field(key: "monitored", emit_null: true)]
  property monitored : Bool?

  @[JSON::Field(key: "absoluteEpisodeNumber", emit_null: true)]
  property absolute_episode_number : Int32?

  @[JSON::Field(key: "sceneAbsoluteEpisodeNumber", emit_null: true)]
  property scene_absolute_episode_number : Int32?

  @[JSON::Field(key: "sceneEpisodeNumber", emit_null: true)]
  property scene_episode_number : Int32?

  @[JSON::Field(key: "sceneSeasonNumber", emit_null: true)]
  property scene_season_number : Int32?

  @[JSON::Field(key: "unverifiedSceneNumbering", emit_null: true)]
  property unverified_scene_numbering : Bool?

  @[JSON::Field(key: "endTime", emit_null: true, converter: Sonarr::TimeConverter)]
  property end_time : Time?

  @[JSON::Field(key: "grabDate", emit_null: true, converter: Sonarr::TimeConverter)]
  property grab_date : Time?

  @[JSON::Field(key: "series", emit_null: true)]
  property series : Sonarr::Model::SeriesResource?

  @[JSON::Field(key: "images", emit_null: true)]
  property images = [] of Sonarr::Model::MediaCover
end
