# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::EpisodesMonitoredResource < Sonarr::Model
  @[JSON::Field(key: "episodeIds")]
  property episode_ids = [] of Int32

  @[JSON::Field(key: "monitored")]
  property monitored : Bool?
end
