# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::EpisodeResourcePagingResource < Sonarr::Model
  @[JSON::Field(key: "page")]
  property page : Int32?

  @[JSON::Field(key: "pageSize")]
  property page_size : Int32?

  @[JSON::Field(key: "sortKey")]
  property sort_key : String?

  @[JSON::Field(key: "sortDirection")]
  property sort_direction : Sonarr::SortDirection?

  @[JSON::Field(key: "totalRecords")]
  property total_records : Int32?

  @[JSON::Field(key: "records")]
  property records = [] of Sonarr::Model::EpisodeResource
end
