# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::EpisodeFileListResource < Sonarr::Model
  @[JSON::Field(key: "episodeFileIds", emit_null: true)]
  property episode_file_ids = [] of Int32

  @[JSON::Field(key: "languages", emit_null: true)]
  property languages = [] of Sonarr::Model::Language

  @[JSON::Field(key: "quality", emit_null: true)]
  property quality : Sonarr::Model::QualityModel?

  @[JSON::Field(key: "sceneName", emit_null: true)]
  property scene_name : String?

  @[JSON::Field(key: "releaseGroup", emit_null: true)]
  property release_group : String?
end
