# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::HealthResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "source", emit_null: true)]
  property source : String?

  @[JSON::Field(key: "type", emit_null: true)]
  property type_field : Sonarr::HealthCheckResult?

  @[JSON::Field(key: "message", emit_null: true)]
  property message : String?

  @[JSON::Field(key: "wikiUrl", emit_null: true)]
  property wiki_url : Sonarr::Model::HttpUri?
end
