# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::HistoryResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "episodeId")]
  property episode_id : Int32?

  @[JSON::Field(key: "seriesId")]
  property series_id : Int32?

  @[JSON::Field(key: "sourceTitle")]
  property source_title : String?

  @[JSON::Field(key: "languages")]
  property languages = [] of Sonarr::Model::Language

  @[JSON::Field(key: "quality")]
  property quality : Sonarr::Model::QualityModel?

  @[JSON::Field(key: "customFormats")]
  property custom_formats = [] of Sonarr::Model::CustomFormatResource

  @[JSON::Field(key: "customFormatScore")]
  property custom_format_score : Int32?

  @[JSON::Field(key: "qualityCutoffNotMet")]
  property quality_cutoff_not_met : Bool?

  @[JSON::Field(key: "date", converter: Sonarr::TimeConverter)]
  property date : Time?

  @[JSON::Field(key: "downloadId")]
  property download_id : String?

  @[JSON::Field(key: "eventType")]
  property event_type : Sonarr::EpisodeHistoryEventType?

  @[JSON::Field(key: "data")]
  property data : Hash(String, String?)?

  @[JSON::Field(key: "episode")]
  property episode : Sonarr::Model::EpisodeResource?

  @[JSON::Field(key: "series")]
  property series : Sonarr::Model::SeriesResource?
end
