# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::HttpUri < Sonarr::Model
  @[JSON::Field(key: "fullUri")]
  property full_uri : String?

  @[JSON::Field(key: "scheme")]
  property scheme : String?

  @[JSON::Field(key: "host")]
  property host : String?

  @[JSON::Field(key: "port")]
  property port : Int32?

  @[JSON::Field(key: "path")]
  property path : String?

  @[JSON::Field(key: "query")]
  property query : String?

  @[JSON::Field(key: "fragment")]
  property fragment : String?
end
