# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::ImportListResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "fields")]
  property fields = [] of Sonarr::Model::Field

  @[JSON::Field(key: "implementationName")]
  property implementation_name : String?

  @[JSON::Field(key: "implementation")]
  property implementation : String?

  @[JSON::Field(key: "configContract")]
  property config_contract : String?

  @[JSON::Field(key: "infoLink")]
  property info_link : String?

  @[JSON::Field(key: "message")]
  property message : Sonarr::Model::ProviderMessage?

  @[JSON::Field(key: "tags")]
  property tags = [] of Int32

  @[JSON::Field(key: "presets")]
  property presets = [] of Sonarr::Model::ImportListResource

  @[JSON::Field(key: "enableAutomaticAdd")]
  property enable_automatic_add : Bool?

  @[JSON::Field(key: "searchForMissingEpisodes")]
  property search_for_missing_episodes : Bool?

  @[JSON::Field(key: "shouldMonitor")]
  property should_monitor : Sonarr::MonitorTypes?

  @[JSON::Field(key: "monitorNewItems")]
  property monitor_new_items : Sonarr::NewItemMonitorTypes?

  @[JSON::Field(key: "rootFolderPath")]
  property root_folder_path : String?

  @[JSON::Field(key: "qualityProfileId")]
  property quality_profile_id : Int32?

  @[JSON::Field(key: "seriesType")]
  property series_type : Sonarr::SeriesTypes?

  @[JSON::Field(key: "seasonFolder")]
  property season_folder : Bool?

  @[JSON::Field(key: "listType")]
  property list_type : Sonarr::ImportListType?

  @[JSON::Field(key: "listOrder")]
  property list_order : Int32?

  @[JSON::Field(key: "minRefreshInterval")]
  property min_refresh_interval : String?
end
