# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::ImportListExclusionResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "tvdbId")]
  property tvdb_id : Int32?

  @[JSON::Field(key: "title")]
  property title : String?
end
