# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::ImportListExclusionBulkResource < Sonarr::Model
  @[JSON::Field(key: "ids")]
  property ids = [] of Int32
end
