# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::ImportRejectionResource < Sonarr::Model
  @[JSON::Field(key: "reason", emit_null: true)]
  property reason : String?

  @[JSON::Field(key: "type", emit_null: true)]
  property type_field : Sonarr::RejectionType?
end
