# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::ImportListConfigResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "listSyncLevel", emit_null: true)]
  property list_sync_level : Sonarr::ListSyncLevelType?

  @[JSON::Field(key: "listSyncTag", emit_null: true)]
  property list_sync_tag : Int32?
end
