# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::ImportListExclusionResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "tvdbId", emit_null: true)]
  property tvdb_id : Int32?

  @[JSON::Field(key: "title", emit_null: true)]
  property title : String?
end
