# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::IndexerConfigResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "minimumAge", emit_null: true)]
  property minimum_age : Int32?

  @[JSON::Field(key: "retention", emit_null: true)]
  property retention : Int32?

  @[JSON::Field(key: "maximumSize", emit_null: true)]
  property maximum_size : Int32?

  @[JSON::Field(key: "rssSyncInterval", emit_null: true)]
  property rss_sync_interval : Int32?
end
