# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::IndexerResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "name", emit_null: true)]
  property name : String?

  @[JSON::Field(key: "fields", emit_null: true)]
  property fields = [] of Sonarr::Model::Field

  @[JSON::Field(key: "implementationName", emit_null: true)]
  property implementation_name : String?

  @[JSON::Field(key: "implementation", emit_null: true)]
  property implementation : String?

  @[JSON::Field(key: "configContract", emit_null: true)]
  property config_contract : String?

  @[JSON::Field(key: "infoLink", emit_null: true)]
  property info_link : String?

  @[JSON::Field(key: "message", emit_null: true)]
  property message : Sonarr::Model::ProviderMessage?

  @[JSON::Field(key: "tags", emit_null: true)]
  property tags = [] of Int32

  @[JSON::Field(key: "presets", emit_null: true)]
  property presets = [] of Sonarr::Model::IndexerResource

  @[JSON::Field(key: "enableRss", emit_null: true)]
  property enable_rss : Bool?

  @[JSON::Field(key: "enableAutomaticSearch", emit_null: true)]
  property enable_automatic_search : Bool?

  @[JSON::Field(key: "enableInteractiveSearch", emit_null: true)]
  property enable_interactive_search : Bool?

  @[JSON::Field(key: "supportsRss", emit_null: true)]
  property supports_rss : Bool?

  @[JSON::Field(key: "supportsSearch", emit_null: true)]
  property supports_search : Bool?

  @[JSON::Field(key: "protocol", emit_null: true)]
  property protocol : Sonarr::DownloadProtocol?

  @[JSON::Field(key: "priority", emit_null: true)]
  property priority : Int32?

  @[JSON::Field(key: "seasonSearchMaximumSingleEpisodeAge", emit_null: true)]
  property season_search_maximum_single_episode_age : Int32?

  @[JSON::Field(key: "downloadClientId", emit_null: true)]
  property download_client_id : Int32?
end
