# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::IndexerBulkResource < Sonarr::Model
  @[JSON::Field(key: "ids")]
  property ids = [] of Int32

  @[JSON::Field(key: "tags")]
  property tags = [] of Int32

  @[JSON::Field(key: "applyTags")]
  property apply_tags : Sonarr::ApplyTags?

  @[JSON::Field(key: "enableRss")]
  property enable_rss : Bool?

  @[JSON::Field(key: "enableAutomaticSearch")]
  property enable_automatic_search : Bool?

  @[JSON::Field(key: "enableInteractiveSearch")]
  property enable_interactive_search : Bool?

  @[JSON::Field(key: "priority")]
  property priority : Int32?
end
