# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::LanguageProfileResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "upgradeAllowed")]
  property upgrade_allowed : Bool?

  @[JSON::Field(key: "cutoff")]
  property cutoff : Sonarr::Model::Language?

  @[JSON::Field(key: "languages")]
  property languages = [] of Sonarr::Model::LanguageProfileItemResource
end
