# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::LanguageProfileResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "name", emit_null: true)]
  property name : String?

  @[JSON::Field(key: "upgradeAllowed", emit_null: true)]
  property upgrade_allowed : Bool?

  @[JSON::Field(key: "cutoff", emit_null: true)]
  property cutoff : Sonarr::Model::Language?

  @[JSON::Field(key: "languages", emit_null: true)]
  property languages = [] of Sonarr::Model::LanguageProfileItemResource
end
