# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::LanguageProfileItemResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "language")]
  property language : Sonarr::Model::Language?

  @[JSON::Field(key: "allowed")]
  property allowed : Bool?
end
