# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::LanguageProfileItemResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "language", emit_null: true)]
  property language : Sonarr::Model::Language?

  @[JSON::Field(key: "allowed", emit_null: true)]
  property allowed : Bool?
end
