# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::LocalizationLanguageResource < Sonarr::Model
  @[JSON::Field(key: "identifier", emit_null: true)]
  property identifier : String?
end
