# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::LogResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "time", emit_null: true, converter: Sonarr::TimeConverter)]
  property time : Time?

  @[JSON::Field(key: "exception", emit_null: true)]
  property exception : String?

  @[JSON::Field(key: "exceptionType", emit_null: true)]
  property exception_type : String?

  @[JSON::Field(key: "level", emit_null: true)]
  property level : String?

  @[JSON::Field(key: "logger", emit_null: true)]
  property logger : String?

  @[JSON::Field(key: "message", emit_null: true)]
  property message : String?

  @[JSON::Field(key: "method", emit_null: true)]
  property method : String?
end
