# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::LogResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "time", converter: Sonarr::TimeConverter)]
  property time : Time?

  @[JSON::Field(key: "exception")]
  property exception : String?

  @[JSON::Field(key: "exceptionType")]
  property exception_type : String?

  @[JSON::Field(key: "level")]
  property level : String?

  @[JSON::Field(key: "logger")]
  property logger : String?

  @[JSON::Field(key: "message")]
  property message : String?

  @[JSON::Field(key: "method")]
  property method : String?
end
