# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::LogFileResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "filename")]
  property filename : String?

  @[JSON::Field(key: "lastWriteTime", converter: Sonarr::TimeConverter)]
  property last_write_time : Time?

  @[JSON::Field(key: "contentsUrl")]
  property contents_url : String?

  @[JSON::Field(key: "downloadUrl")]
  property download_url : String?
end
