# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::LogFileResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "filename", emit_null: true)]
  property filename : String?

  @[JSON::Field(key: "lastWriteTime", emit_null: true, converter: Sonarr::TimeConverter)]
  property last_write_time : Time?

  @[JSON::Field(key: "contentsUrl", emit_null: true)]
  property contents_url : String?

  @[JSON::Field(key: "downloadUrl", emit_null: true)]
  property download_url : String?
end
