# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::ManualImportResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "path", emit_null: true)]
  property path : String?

  @[JSON::Field(key: "relativePath", emit_null: true)]
  property relative_path : String?

  @[JSON::Field(key: "folderName", emit_null: true)]
  property folder_name : String?

  @[JSON::Field(key: "name", emit_null: true)]
  property name : String?

  @[JSON::Field(key: "size", emit_null: true)]
  property size : Int64?

  @[JSON::Field(key: "series", emit_null: true)]
  property series : Sonarr::Model::SeriesResource?

  @[JSON::Field(key: "seasonNumber", emit_null: true)]
  property season_number : Int32?

  @[JSON::Field(key: "episodes", emit_null: true)]
  property episodes = [] of Sonarr::Model::EpisodeResource

  @[JSON::Field(key: "episodeFileId", emit_null: true)]
  property episode_file_id : Int32?

  @[JSON::Field(key: "releaseGroup", emit_null: true)]
  property release_group : String?

  @[JSON::Field(key: "quality", emit_null: true)]
  property quality : Sonarr::Model::QualityModel?

  @[JSON::Field(key: "languages", emit_null: true)]
  property languages = [] of Sonarr::Model::Language

  @[JSON::Field(key: "qualityWeight", emit_null: true)]
  property quality_weight : Int32?

  @[JSON::Field(key: "downloadId", emit_null: true)]
  property download_id : String?

  @[JSON::Field(key: "customFormats", emit_null: true)]
  property custom_formats = [] of Sonarr::Model::CustomFormatResource

  @[JSON::Field(key: "customFormatScore", emit_null: true)]
  property custom_format_score : Int32?

  @[JSON::Field(key: "indexerFlags", emit_null: true)]
  property indexer_flags : Int32?

  @[JSON::Field(key: "releaseType", emit_null: true)]
  property release_type : Sonarr::ReleaseType?

  @[JSON::Field(key: "rejections", emit_null: true)]
  property rejections = [] of Sonarr::Model::ImportRejectionResource
end
