# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::ManualImportReprocessResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "path")]
  property path : String?

  @[JSON::Field(key: "seriesId")]
  property series_id : Int32?

  @[JSON::Field(key: "seasonNumber")]
  property season_number : Int32?

  @[JSON::Field(key: "episodes")]
  property episodes = [] of Sonarr::Model::EpisodeResource

  @[JSON::Field(key: "episodeIds")]
  property episode_ids = [] of Int32

  @[JSON::Field(key: "quality")]
  property quality : Sonarr::Model::QualityModel?

  @[JSON::Field(key: "languages")]
  property languages = [] of Sonarr::Model::Language

  @[JSON::Field(key: "releaseGroup")]
  property release_group : String?

  @[JSON::Field(key: "downloadId")]
  property download_id : String?

  @[JSON::Field(key: "customFormats")]
  property custom_formats = [] of Sonarr::Model::CustomFormatResource

  @[JSON::Field(key: "customFormatScore")]
  property custom_format_score : Int32?

  @[JSON::Field(key: "indexerFlags")]
  property indexer_flags : Int32?

  @[JSON::Field(key: "releaseType")]
  property release_type : Sonarr::ReleaseType?

  @[JSON::Field(key: "rejections")]
  property rejections = [] of Sonarr::Model::ImportRejectionResource
end
