# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::MediaCover < Sonarr::Model
  @[JSON::Field(key: "coverType")]
  property cover_type : Sonarr::MediaCoverTypes?

  @[JSON::Field(key: "url")]
  property url : String?

  @[JSON::Field(key: "remoteUrl")]
  property remote_url : String?
end
