# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::MediaManagementConfigResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "autoUnmonitorPreviouslyDownloadedEpisodes")]
  property auto_unmonitor_previously_downloaded_episodes : Bool?

  @[JSON::Field(key: "recycleBin")]
  property recycle_bin : String?

  @[JSON::Field(key: "recycleBinCleanupDays")]
  property recycle_bin_cleanup_days : Int32?

  @[JSON::Field(key: "downloadPropersAndRepacks")]
  property download_propers_and_repacks : Sonarr::ProperDownloadTypes?

  @[JSON::Field(key: "createEmptySeriesFolders")]
  property create_empty_series_folders : Bool?

  @[JSON::Field(key: "deleteEmptyFolders")]
  property delete_empty_folders : Bool?

  @[JSON::Field(key: "fileDate")]
  property file_date : Sonarr::FileDateType?

  @[JSON::Field(key: "rescanAfterRefresh")]
  property rescan_after_refresh : Sonarr::RescanAfterRefreshType?

  @[JSON::Field(key: "setPermissionsLinux")]
  property set_permissions_linux : Bool?

  @[JSON::Field(key: "chmodFolder")]
  property chmod_folder : String?

  @[JSON::Field(key: "chownGroup")]
  property chown_group : String?

  @[JSON::Field(key: "episodeTitleRequired")]
  property episode_title_required : Sonarr::EpisodeTitleRequiredType?

  @[JSON::Field(key: "skipFreeSpaceCheckWhenImporting")]
  property skip_free_space_check_when_importing : Bool?

  @[JSON::Field(key: "minimumFreeSpaceWhenImporting")]
  property minimum_free_space_when_importing : Int32?

  @[JSON::Field(key: "copyUsingHardlinks")]
  property copy_using_hardlinks : Bool?

  @[JSON::Field(key: "useScriptImport")]
  property use_script_import : Bool?

  @[JSON::Field(key: "scriptImportPath")]
  property script_import_path : String?

  @[JSON::Field(key: "importExtraFiles")]
  property import_extra_files : Bool?

  @[JSON::Field(key: "extraFileExtensions")]
  property extra_file_extensions : String?

  @[JSON::Field(key: "enableMediaInfo")]
  property enable_media_info : Bool?
end
