# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::MediaCover < Sonarr::Model
  @[JSON::Field(key: "coverType", emit_null: true)]
  property cover_type : Sonarr::MediaCoverTypes?

  @[JSON::Field(key: "url", emit_null: true)]
  property url : String?

  @[JSON::Field(key: "remoteUrl", emit_null: true)]
  property remote_url : String?
end
