# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::MediaInfoResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "audioBitrate")]
  property audio_bitrate : Int64?

  @[JSON::Field(key: "audioChannels")]
  property audio_channels : Float64?

  @[JSON::Field(key: "audioCodec")]
  property audio_codec : String?

  @[JSON::Field(key: "audioLanguages")]
  property audio_languages : String?

  @[JSON::Field(key: "audioStreamCount")]
  property audio_stream_count : Int32?

  @[JSON::Field(key: "videoBitDepth")]
  property video_bit_depth : Int32?

  @[JSON::Field(key: "videoBitrate")]
  property video_bitrate : Int64?

  @[JSON::Field(key: "videoCodec")]
  property video_codec : String?

  @[JSON::Field(key: "videoFps")]
  property video_fps : Float64?

  @[JSON::Field(key: "videoDynamicRange")]
  property video_dynamic_range : String?

  @[JSON::Field(key: "videoDynamicRangeType")]
  property video_dynamic_range_type : String?

  @[JSON::Field(key: "resolution")]
  property resolution : String?

  @[JSON::Field(key: "runTime")]
  property run_time : String?

  @[JSON::Field(key: "scanType")]
  property scan_type : String?

  @[JSON::Field(key: "subtitles")]
  property subtitles : String?
end
