# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::MonitoringOptions < Sonarr::Model
  @[JSON::Field(key: "ignoreEpisodesWithFiles")]
  property ignore_episodes_with_files : Bool?

  @[JSON::Field(key: "ignoreEpisodesWithoutFiles")]
  property ignore_episodes_without_files : Bool?

  @[JSON::Field(key: "monitor")]
  property monitor : Sonarr::MonitorTypes?
end
