# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::NamingConfigResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "renameEpisodes", emit_null: true)]
  property rename_episodes : Bool?

  @[JSON::Field(key: "replaceIllegalCharacters", emit_null: true)]
  property replace_illegal_characters : Bool?

  @[JSON::Field(key: "colonReplacementFormat", emit_null: true)]
  property colon_replacement_format : Int32?

  @[JSON::Field(key: "customColonReplacementFormat", emit_null: true)]
  property custom_colon_replacement_format : String?

  @[JSON::Field(key: "multiEpisodeStyle", emit_null: true)]
  property multi_episode_style : Int32?

  @[JSON::Field(key: "standardEpisodeFormat", emit_null: true)]
  property standard_episode_format : String?

  @[JSON::Field(key: "dailyEpisodeFormat", emit_null: true)]
  property daily_episode_format : String?

  @[JSON::Field(key: "animeEpisodeFormat", emit_null: true)]
  property anime_episode_format : String?

  @[JSON::Field(key: "seriesFolderFormat", emit_null: true)]
  property series_folder_format : String?

  @[JSON::Field(key: "seasonFolderFormat", emit_null: true)]
  property season_folder_format : String?

  @[JSON::Field(key: "specialsFolderFormat", emit_null: true)]
  property specials_folder_format : String?
end
