# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::PingResource < Sonarr::Model
  @[JSON::Field(key: "status", emit_null: true)]
  property status : String?
end
