# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::ProviderMessage < Sonarr::Model
  @[JSON::Field(key: "message", emit_null: true)]
  property message : String?

  @[JSON::Field(key: "type", emit_null: true)]
  property type_field : Sonarr::ProviderMessageType?
end
