# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::QualityProfileResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "name", emit_null: true)]
  property name : String?

  @[JSON::Field(key: "upgradeAllowed", emit_null: true)]
  property upgrade_allowed : Bool?

  @[JSON::Field(key: "cutoff", emit_null: true)]
  property cutoff : Int32?

  @[JSON::Field(key: "items", emit_null: true)]
  property items = [] of Sonarr::Model::QualityProfileQualityItemResource

  @[JSON::Field(key: "minFormatScore", emit_null: true)]
  property min_format_score : Int32?

  @[JSON::Field(key: "cutoffFormatScore", emit_null: true)]
  property cutoff_format_score : Int32?

  @[JSON::Field(key: "minUpgradeFormatScore", emit_null: true)]
  property min_upgrade_format_score : Int32?

  @[JSON::Field(key: "formatItems", emit_null: true)]
  property format_items = [] of Sonarr::Model::ProfileFormatItemResource
end
