# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::QualityDefinitionLimitsResource < Sonarr::Model
  @[JSON::Field(key: "min")]
  property min : Int32?

  @[JSON::Field(key: "max")]
  property max : Int32?
end
