# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::QualityDefinitionResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "quality")]
  property quality : Sonarr::Model::Quality?

  @[JSON::Field(key: "title")]
  property title : String?

  @[JSON::Field(key: "weight")]
  property weight : Int32?

  @[JSON::Field(key: "minSize")]
  property min_size : Float64?

  @[JSON::Field(key: "maxSize")]
  property max_size : Float64?

  @[JSON::Field(key: "preferredSize")]
  property preferred_size : Float64?
end
