# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::Quality < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "source")]
  property source : Sonarr::QualitySource?

  @[JSON::Field(key: "resolution")]
  property resolution : Int32?
end
