# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::QualityModel < Sonarr::Model
  @[JSON::Field(key: "quality")]
  property quality : Sonarr::Model::Quality?

  @[JSON::Field(key: "revision")]
  property revision : Sonarr::Model::Revision?
end
