# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::QualityDefinitionLimitsResource < Sonarr::Model
  @[JSON::Field(key: "min", emit_null: true)]
  property min : Int32?

  @[JSON::Field(key: "max", emit_null: true)]
  property max : Int32?
end
