# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::QualityProfileQualityItemResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "name", emit_null: true)]
  property name : String?

  @[JSON::Field(key: "quality", emit_null: true)]
  property quality : Sonarr::Model::Quality?

  @[JSON::Field(key: "items", emit_null: true)]
  property items = [] of Sonarr::Model::QualityProfileQualityItemResource

  @[JSON::Field(key: "allowed", emit_null: true)]
  property allowed : Bool?
end
