# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::QualityDefinitionResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "quality", emit_null: true)]
  property quality : Sonarr::Model::Quality?

  @[JSON::Field(key: "title", emit_null: true)]
  property title : String?

  @[JSON::Field(key: "weight", emit_null: true)]
  property weight : Int32?

  @[JSON::Field(key: "minSize", emit_null: true)]
  property min_size : Float64?

  @[JSON::Field(key: "maxSize", emit_null: true)]
  property max_size : Float64?

  @[JSON::Field(key: "preferredSize", emit_null: true)]
  property preferred_size : Float64?
end
