# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::QueueResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "seriesId", emit_null: true)]
  property series_id : Int32?

  @[JSON::Field(key: "episodeId", emit_null: true)]
  property episode_id : Int32?

  @[JSON::Field(key: "seasonNumber", emit_null: true)]
  property season_number : Int32?

  @[JSON::Field(key: "series", emit_null: true)]
  property series : Sonarr::Model::SeriesResource?

  @[JSON::Field(key: "episode", emit_null: true)]
  property episode : Sonarr::Model::EpisodeResource?

  @[JSON::Field(key: "languages", emit_null: true)]
  property languages = [] of Sonarr::Model::Language

  @[JSON::Field(key: "quality", emit_null: true)]
  property quality : Sonarr::Model::QualityModel?

  @[JSON::Field(key: "customFormats", emit_null: true)]
  property custom_formats = [] of Sonarr::Model::CustomFormatResource

  @[JSON::Field(key: "customFormatScore", emit_null: true)]
  property custom_format_score : Int32?

  @[JSON::Field(key: "size", emit_null: true)]
  property size : Float64?

  @[JSON::Field(key: "title", emit_null: true)]
  property title : String?

  @[JSON::Field(key: "estimatedCompletionTime", emit_null: true, converter: Sonarr::TimeConverter)]
  property estimated_completion_time : Time?

  @[JSON::Field(key: "added", emit_null: true, converter: Sonarr::TimeConverter)]
  property added : Time?

  @[JSON::Field(key: "status", emit_null: true)]
  property status : Sonarr::QueueStatus?

  @[JSON::Field(key: "trackedDownloadStatus", emit_null: true)]
  property tracked_download_status : Sonarr::TrackedDownloadStatus?

  @[JSON::Field(key: "trackedDownloadState", emit_null: true)]
  property tracked_download_state : Sonarr::TrackedDownloadState?

  @[JSON::Field(key: "statusMessages", emit_null: true)]
  property status_messages = [] of Sonarr::Model::TrackedDownloadStatusMessage

  @[JSON::Field(key: "errorMessage", emit_null: true)]
  property error_message : String?

  @[JSON::Field(key: "downloadId", emit_null: true)]
  property download_id : String?

  @[JSON::Field(key: "protocol", emit_null: true)]
  property protocol : Sonarr::DownloadProtocol?

  @[JSON::Field(key: "downloadClient", emit_null: true)]
  property download_client : String?

  @[JSON::Field(key: "downloadClientHasPostImportCategory", emit_null: true)]
  property download_client_has_post_import_category : Bool?

  @[JSON::Field(key: "indexer", emit_null: true)]
  property indexer : String?

  @[JSON::Field(key: "outputPath", emit_null: true)]
  property output_path : String?

  @[JSON::Field(key: "episodeHasFile", emit_null: true)]
  property episode_has_file : Bool?

  @[JSON::Field(key: "sizeleft", emit_null: true)]
  property sizeleft : Float64?

  @[JSON::Field(key: "timeleft", emit_null: true)]
  property timeleft : String?
end
