# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::QueueStatusResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "totalCount", emit_null: true)]
  property total_count : Int32?

  @[JSON::Field(key: "count", emit_null: true)]
  property count : Int32?

  @[JSON::Field(key: "unknownCount", emit_null: true)]
  property unknown_count : Int32?

  @[JSON::Field(key: "errors", emit_null: true)]
  property errors : Bool?

  @[JSON::Field(key: "warnings", emit_null: true)]
  property warnings : Bool?

  @[JSON::Field(key: "unknownErrors", emit_null: true)]
  property unknown_errors : Bool?

  @[JSON::Field(key: "unknownWarnings", emit_null: true)]
  property unknown_warnings : Bool?
end
