# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::QueueResourcePagingResource < Sonarr::Model
  @[JSON::Field(key: "page", emit_null: true)]
  property page : Int32?

  @[JSON::Field(key: "pageSize", emit_null: true)]
  property page_size : Int32?

  @[JSON::Field(key: "sortKey", emit_null: true)]
  property sort_key : String?

  @[JSON::Field(key: "sortDirection", emit_null: true)]
  property sort_direction : Sonarr::SortDirection?

  @[JSON::Field(key: "totalRecords", emit_null: true)]
  property total_records : Int32?

  @[JSON::Field(key: "records", emit_null: true)]
  property records = [] of Sonarr::Model::QueueResource
end
