# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::Ratings < Sonarr::Model
  @[JSON::Field(key: "votes", emit_null: true)]
  property votes : Int32?

  @[JSON::Field(key: "value", emit_null: true)]
  property value : Float64?
end
