# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::ReleaseProfileResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "enabled")]
  property enabled : Bool?

  @[JSON::Field(key: "required")]
  property required : JSON::Any?

  @[JSON::Field(key: "ignored")]
  property ignored : JSON::Any?

  @[JSON::Field(key: "indexerId")]
  property indexer_id : Int32?

  @[JSON::Field(key: "tags")]
  property tags = [] of Int32
end
