# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::ReleaseProfileResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "name", emit_null: true)]
  property name : String?

  @[JSON::Field(key: "enabled", emit_null: true)]
  property enabled : Bool?

  @[JSON::Field(key: "required", emit_null: true)]
  property required : JSON::Any?

  @[JSON::Field(key: "ignored", emit_null: true)]
  property ignored : JSON::Any?

  @[JSON::Field(key: "indexerId", emit_null: true)]
  property indexer_id : Int32?

  @[JSON::Field(key: "tags", emit_null: true)]
  property tags = [] of Int32
end
