# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::ReleaseEpisodeResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "seasonNumber", emit_null: true)]
  property season_number : Int32?

  @[JSON::Field(key: "episodeNumber", emit_null: true)]
  property episode_number : Int32?

  @[JSON::Field(key: "absoluteEpisodeNumber", emit_null: true)]
  property absolute_episode_number : Int32?

  @[JSON::Field(key: "title", emit_null: true)]
  property title : String?
end
