# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::ReleaseResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "guid", emit_null: true)]
  property guid : String?

  @[JSON::Field(key: "quality", emit_null: true)]
  property quality : Sonarr::Model::QualityModel?

  @[JSON::Field(key: "qualityWeight", emit_null: true)]
  property quality_weight : Int32?

  @[JSON::Field(key: "age", emit_null: true)]
  property age : Int32?

  @[JSON::Field(key: "ageHours", emit_null: true)]
  property age_hours : Float64?

  @[JSON::Field(key: "ageMinutes", emit_null: true)]
  property age_minutes : Float64?

  @[JSON::Field(key: "size", emit_null: true)]
  property size : Int64?

  @[JSON::Field(key: "indexerId", emit_null: true)]
  property indexer_id : Int32?

  @[JSON::Field(key: "indexer", emit_null: true)]
  property indexer : String?

  @[JSON::Field(key: "releaseGroup", emit_null: true)]
  property release_group : String?

  @[JSON::Field(key: "subGroup", emit_null: true)]
  property sub_group : String?

  @[JSON::Field(key: "releaseHash", emit_null: true)]
  property release_hash : String?

  @[JSON::Field(key: "title", emit_null: true)]
  property title : String?

  @[JSON::Field(key: "fullSeason", emit_null: true)]
  property full_season : Bool?

  @[JSON::Field(key: "sceneSource", emit_null: true)]
  property scene_source : Bool?

  @[JSON::Field(key: "seasonNumber", emit_null: true)]
  property season_number : Int32?

  @[JSON::Field(key: "languages", emit_null: true)]
  property languages = [] of Sonarr::Model::Language

  @[JSON::Field(key: "languageWeight", emit_null: true)]
  property language_weight : Int32?

  @[JSON::Field(key: "airDate", emit_null: true)]
  property air_date : String?

  @[JSON::Field(key: "seriesTitle", emit_null: true)]
  property series_title : String?

  @[JSON::Field(key: "episodeNumbers", emit_null: true)]
  property episode_numbers = [] of Int32

  @[JSON::Field(key: "absoluteEpisodeNumbers", emit_null: true)]
  property absolute_episode_numbers = [] of Int32

  @[JSON::Field(key: "mappedSeasonNumber", emit_null: true)]
  property mapped_season_number : Int32?

  @[JSON::Field(key: "mappedEpisodeNumbers", emit_null: true)]
  property mapped_episode_numbers = [] of Int32

  @[JSON::Field(key: "mappedAbsoluteEpisodeNumbers", emit_null: true)]
  property mapped_absolute_episode_numbers = [] of Int32

  @[JSON::Field(key: "mappedSeriesId", emit_null: true)]
  property mapped_series_id : Int32?

  @[JSON::Field(key: "mappedEpisodeInfo", emit_null: true)]
  property mapped_episode_info = [] of Sonarr::Model::ReleaseEpisodeResource

  @[JSON::Field(key: "approved", emit_null: true)]
  property approved : Bool?

  @[JSON::Field(key: "temporarilyRejected", emit_null: true)]
  property temporarily_rejected : Bool?

  @[JSON::Field(key: "rejected", emit_null: true)]
  property rejected : Bool?

  @[JSON::Field(key: "tvdbId", emit_null: true)]
  property tvdb_id : Int32?

  @[JSON::Field(key: "tvRageId", emit_null: true)]
  property tv_rage_id : Int32?

  @[JSON::Field(key: "imdbId", emit_null: true)]
  property imdb_id : String?

  @[JSON::Field(key: "rejections", emit_null: true)]
  property rejections = [] of String

  @[JSON::Field(key: "publishDate", emit_null: true, converter: Sonarr::TimeConverter)]
  property publish_date : Time?

  @[JSON::Field(key: "commentUrl", emit_null: true)]
  property comment_url : String?

  @[JSON::Field(key: "downloadUrl", emit_null: true)]
  property download_url : String?

  @[JSON::Field(key: "infoUrl", emit_null: true)]
  property info_url : String?

  @[JSON::Field(key: "episodeRequested", emit_null: true)]
  property episode_requested : Bool?

  @[JSON::Field(key: "downloadAllowed", emit_null: true)]
  property download_allowed : Bool?

  @[JSON::Field(key: "releaseWeight", emit_null: true)]
  property release_weight : Int32?

  @[JSON::Field(key: "customFormats", emit_null: true)]
  property custom_formats = [] of Sonarr::Model::CustomFormatResource

  @[JSON::Field(key: "customFormatScore", emit_null: true)]
  property custom_format_score : Int32?

  @[JSON::Field(key: "sceneMapping", emit_null: true)]
  property scene_mapping : Sonarr::Model::AlternateTitleResource?

  @[JSON::Field(key: "magnetUrl", emit_null: true)]
  property magnet_url : String?

  @[JSON::Field(key: "infoHash", emit_null: true)]
  property info_hash : String?

  @[JSON::Field(key: "seeders", emit_null: true)]
  property seeders : Int32?

  @[JSON::Field(key: "leechers", emit_null: true)]
  property leechers : Int32?

  @[JSON::Field(key: "protocol", emit_null: true)]
  property protocol : Sonarr::DownloadProtocol?

  @[JSON::Field(key: "indexerFlags", emit_null: true)]
  property indexer_flags : Int32?

  @[JSON::Field(key: "isDaily", emit_null: true)]
  property is_daily : Bool?

  @[JSON::Field(key: "isAbsoluteNumbering", emit_null: true)]
  property is_absolute_numbering : Bool?

  @[JSON::Field(key: "isPossibleSpecialEpisode", emit_null: true)]
  property is_possible_special_episode : Bool?

  @[JSON::Field(key: "special", emit_null: true)]
  property special : Bool?

  @[JSON::Field(key: "seriesId", emit_null: true)]
  property series_id : Int32?

  @[JSON::Field(key: "episodeId", emit_null: true)]
  property episode_id : Int32?

  @[JSON::Field(key: "episodeIds", emit_null: true)]
  property episode_ids = [] of Int32

  @[JSON::Field(key: "downloadClientId", emit_null: true)]
  property download_client_id : Int32?

  @[JSON::Field(key: "downloadClient", emit_null: true)]
  property download_client : String?

  @[JSON::Field(key: "shouldOverride", emit_null: true)]
  property should_override : Bool?
end
