# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::RemotePathMappingResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "host", emit_null: true)]
  property host : String?

  @[JSON::Field(key: "remotePath", emit_null: true)]
  property remote_path : String?

  @[JSON::Field(key: "localPath", emit_null: true)]
  property local_path : String?
end
