# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::RenameEpisodeResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "seriesId", emit_null: true)]
  property series_id : Int32?

  @[JSON::Field(key: "seasonNumber", emit_null: true)]
  property season_number : Int32?

  @[JSON::Field(key: "episodeNumbers", emit_null: true)]
  property episode_numbers = [] of Int32

  @[JSON::Field(key: "episodeFileId", emit_null: true)]
  property episode_file_id : Int32?

  @[JSON::Field(key: "existingPath", emit_null: true)]
  property existing_path : String?

  @[JSON::Field(key: "newPath", emit_null: true)]
  property new_path : String?
end
