# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::RenameEpisodeResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "seriesId")]
  property series_id : Int32?

  @[JSON::Field(key: "seasonNumber")]
  property season_number : Int32?

  @[JSON::Field(key: "episodeNumbers")]
  property episode_numbers = [] of Int32

  @[JSON::Field(key: "episodeFileId")]
  property episode_file_id : Int32?

  @[JSON::Field(key: "existingPath")]
  property existing_path : String?

  @[JSON::Field(key: "newPath")]
  property new_path : String?
end
