# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::Revision < Sonarr::Model
  @[JSON::Field(key: "version", emit_null: true)]
  property version : Int32?

  @[JSON::Field(key: "real", emit_null: true)]
  property real : Int32?

  @[JSON::Field(key: "isRepack", emit_null: true)]
  property is_repack : Bool?
end
