# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::RootFolderResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "path", emit_null: true)]
  property path : String?

  @[JSON::Field(key: "accessible", emit_null: true)]
  property accessible : Bool?

  @[JSON::Field(key: "freeSpace", emit_null: true)]
  property free_space : Int64?

  @[JSON::Field(key: "unmappedFolders", emit_null: true)]
  property unmapped_folders = [] of Sonarr::Model::UnmappedFolder
end
