# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::SeasonPassSeriesResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "monitored", emit_null: true)]
  property monitored : Bool?

  @[JSON::Field(key: "seasons", emit_null: true)]
  property seasons = [] of Sonarr::Model::SeasonResource
end
