# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::SeasonResource < Sonarr::Model
  @[JSON::Field(key: "seasonNumber", emit_null: true)]
  property season_number : Int32?

  @[JSON::Field(key: "monitored", emit_null: true)]
  property monitored : Bool?

  @[JSON::Field(key: "statistics", emit_null: true)]
  property statistics : Sonarr::Model::SeasonStatisticsResource?

  @[JSON::Field(key: "images", emit_null: true)]
  property images = [] of Sonarr::Model::MediaCover
end
