# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::SeasonPassResource < Sonarr::Model
  @[JSON::Field(key: "series")]
  property series = [] of Sonarr::Model::SeasonPassSeriesResource

  @[JSON::Field(key: "monitoringOptions")]
  property monitoring_options : Sonarr::Model::MonitoringOptions?
end
