# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::SelectOption < Sonarr::Model
  @[JSON::Field(key: "value", emit_null: true)]
  property value : Int32?

  @[JSON::Field(key: "name", emit_null: true)]
  property name : String?

  @[JSON::Field(key: "order", emit_null: true)]
  property order : Int32?

  @[JSON::Field(key: "hint", emit_null: true)]
  property hint : String?
end
