# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::SelectOption < Sonarr::Model
  @[JSON::Field(key: "value")]
  property value : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "order")]
  property order : Int32?

  @[JSON::Field(key: "hint")]
  property hint : String?
end
