# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::SeriesTitleInfo < Sonarr::Model
  @[JSON::Field(key: "title", emit_null: true)]
  property title : String?

  @[JSON::Field(key: "titleWithoutYear", emit_null: true)]
  property title_without_year : String?

  @[JSON::Field(key: "year", emit_null: true)]
  property year : Int32?

  @[JSON::Field(key: "allTitles", emit_null: true)]
  property all_titles = [] of String
end
