# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::SeriesStatisticsResource < Sonarr::Model
  @[JSON::Field(key: "seasonCount")]
  property season_count : Int32?

  @[JSON::Field(key: "episodeFileCount")]
  property episode_file_count : Int32?

  @[JSON::Field(key: "episodeCount")]
  property episode_count : Int32?

  @[JSON::Field(key: "totalEpisodeCount")]
  property total_episode_count : Int32?

  @[JSON::Field(key: "sizeOnDisk")]
  property size_on_disk : Int64?

  @[JSON::Field(key: "releaseGroups")]
  property release_groups = [] of String

  @[JSON::Field(key: "percentOfEpisodes")]
  property percent_of_episodes : Float64?
end
