# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::SeriesTitleInfo < Sonarr::Model
  @[JSON::Field(key: "title")]
  property title : String?

  @[JSON::Field(key: "titleWithoutYear")]
  property title_without_year : String?

  @[JSON::Field(key: "year")]
  property year : Int32?

  @[JSON::Field(key: "allTitles")]
  property all_titles = [] of String
end
