# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::SeriesEditorResource < Sonarr::Model
  @[JSON::Field(key: "seriesIds", emit_null: true)]
  property series_ids = [] of Int32

  @[JSON::Field(key: "monitored", emit_null: true)]
  property monitored : Bool?

  @[JSON::Field(key: "monitorNewItems", emit_null: true)]
  property monitor_new_items : Sonarr::NewItemMonitorTypes?

  @[JSON::Field(key: "qualityProfileId", emit_null: true)]
  property quality_profile_id : Int32?

  @[JSON::Field(key: "seriesType", emit_null: true)]
  property series_type : Sonarr::SeriesTypes?

  @[JSON::Field(key: "seasonFolder", emit_null: true)]
  property season_folder : Bool?

  @[JSON::Field(key: "rootFolderPath", emit_null: true)]
  property root_folder_path : String?

  @[JSON::Field(key: "tags", emit_null: true)]
  property tags = [] of Int32

  @[JSON::Field(key: "applyTags", emit_null: true)]
  property apply_tags : Sonarr::ApplyTags?

  @[JSON::Field(key: "moveFiles", emit_null: true)]
  property move_files : Bool?

  @[JSON::Field(key: "deleteFiles", emit_null: true)]
  property delete_files : Bool?

  @[JSON::Field(key: "addImportListExclusion", emit_null: true)]
  property add_import_list_exclusion : Bool?
end
