# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::SeriesStatisticsResource < Sonarr::Model
  @[JSON::Field(key: "seasonCount", emit_null: true)]
  property season_count : Int32?

  @[JSON::Field(key: "episodeFileCount", emit_null: true)]
  property episode_file_count : Int32?

  @[JSON::Field(key: "episodeCount", emit_null: true)]
  property episode_count : Int32?

  @[JSON::Field(key: "totalEpisodeCount", emit_null: true)]
  property total_episode_count : Int32?

  @[JSON::Field(key: "sizeOnDisk", emit_null: true)]
  property size_on_disk : Int64?

  @[JSON::Field(key: "releaseGroups", emit_null: true)]
  property release_groups = [] of String

  @[JSON::Field(key: "percentOfEpisodes", emit_null: true)]
  property percent_of_episodes : Float64?
end
