# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::SystemResource < Sonarr::Model
  @[JSON::Field(key: "appName")]
  property app_name : String?

  @[JSON::Field(key: "instanceName")]
  property instance_name : String?

  @[JSON::Field(key: "version")]
  property version : String?

  @[JSON::Field(key: "buildTime", converter: Sonarr::TimeConverter)]
  property build_time : Time?

  @[JSON::Field(key: "isDebug")]
  property is_debug : Bool?

  @[JSON::Field(key: "isProduction")]
  property is_production : Bool?

  @[JSON::Field(key: "isAdmin")]
  property is_admin : Bool?

  @[JSON::Field(key: "isUserInteractive")]
  property is_user_interactive : Bool?

  @[JSON::Field(key: "startupPath")]
  property startup_path : String?

  @[JSON::Field(key: "appData")]
  property app_data : String?

  @[JSON::Field(key: "osName")]
  property os_name : String?

  @[JSON::Field(key: "osVersion")]
  property os_version : String?

  @[JSON::Field(key: "isNetCore")]
  property is_net_core : Bool?

  @[JSON::Field(key: "isLinux")]
  property is_linux : Bool?

  @[JSON::Field(key: "isOsx")]
  property is_osx : Bool?

  @[JSON::Field(key: "isWindows")]
  property is_windows : Bool?

  @[JSON::Field(key: "isDocker")]
  property is_docker : Bool?

  @[JSON::Field(key: "mode")]
  property mode : Sonarr::RuntimeMode?

  @[JSON::Field(key: "branch")]
  property branch : String?

  @[JSON::Field(key: "authentication")]
  property authentication : Sonarr::AuthenticationType?

  @[JSON::Field(key: "sqliteVersion")]
  property sqlite_version : String?

  @[JSON::Field(key: "migrationVersion")]
  property migration_version : Int32?

  @[JSON::Field(key: "urlBase")]
  property url_base : String?

  @[JSON::Field(key: "runtimeVersion")]
  property runtime_version : String?

  @[JSON::Field(key: "runtimeName")]
  property runtime_name : String?

  @[JSON::Field(key: "startTime", converter: Sonarr::TimeConverter)]
  property start_time : Time?

  @[JSON::Field(key: "packageVersion")]
  property package_version : String?

  @[JSON::Field(key: "packageAuthor")]
  property package_author : String?

  @[JSON::Field(key: "packageUpdateMechanism")]
  property package_update_mechanism : Sonarr::UpdateMechanism?

  @[JSON::Field(key: "packageUpdateMechanismMessage")]
  property package_update_mechanism_message : String?

  @[JSON::Field(key: "databaseVersion")]
  property database_version : String?

  @[JSON::Field(key: "databaseType")]
  property database_type : Sonarr::DatabaseType?
end
