# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::TagResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "label", emit_null: true)]
  property label : String?
end
