# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::TagDetailsResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "label", emit_null: true)]
  property label : String?

  @[JSON::Field(key: "delayProfileIds", emit_null: true)]
  property delay_profile_ids = [] of Int32

  @[JSON::Field(key: "importListIds", emit_null: true)]
  property import_list_ids = [] of Int32

  @[JSON::Field(key: "notificationIds", emit_null: true)]
  property notification_ids = [] of Int32

  @[JSON::Field(key: "restrictionIds", emit_null: true)]
  property restriction_ids = [] of Int32

  @[JSON::Field(key: "indexerIds", emit_null: true)]
  property indexer_ids = [] of Int32

  @[JSON::Field(key: "downloadClientIds", emit_null: true)]
  property download_client_ids = [] of Int32

  @[JSON::Field(key: "autoTagIds", emit_null: true)]
  property auto_tag_ids = [] of Int32

  @[JSON::Field(key: "seriesIds", emit_null: true)]
  property series_ids = [] of Int32
end
