# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::TagDetailsResource < Sonarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "label")]
  property label : String?

  @[JSON::Field(key: "delayProfileIds")]
  property delay_profile_ids = [] of Int32

  @[JSON::Field(key: "importListIds")]
  property import_list_ids = [] of Int32

  @[JSON::Field(key: "notificationIds")]
  property notification_ids = [] of Int32

  @[JSON::Field(key: "restrictionIds")]
  property restriction_ids = [] of Int32

  @[JSON::Field(key: "indexerIds")]
  property indexer_ids = [] of Int32

  @[JSON::Field(key: "downloadClientIds")]
  property download_client_ids = [] of Int32

  @[JSON::Field(key: "autoTagIds")]
  property auto_tag_ids = [] of Int32

  @[JSON::Field(key: "seriesIds")]
  property series_ids = [] of Int32
end
