# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::TrackedDownloadStatusMessage < Sonarr::Model
  @[JSON::Field(key: "title")]
  property title : String?

  @[JSON::Field(key: "messages")]
  property messages = [] of String
end
