# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::TrackedDownloadStatusMessage < Sonarr::Model
  @[JSON::Field(key: "title", emit_null: true)]
  property title : String?

  @[JSON::Field(key: "messages", emit_null: true)]
  property messages = [] of String
end
