# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::UiConfigResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "firstDayOfWeek", emit_null: true)]
  property first_day_of_week : Int32?

  @[JSON::Field(key: "calendarWeekColumnHeader", emit_null: true)]
  property calendar_week_column_header : String?

  @[JSON::Field(key: "shortDateFormat", emit_null: true)]
  property short_date_format : String?

  @[JSON::Field(key: "longDateFormat", emit_null: true)]
  property long_date_format : String?

  @[JSON::Field(key: "timeFormat", emit_null: true)]
  property time_format : String?

  @[JSON::Field(key: "showRelativeDates", emit_null: true)]
  property show_relative_dates : Bool?

  @[JSON::Field(key: "enableColorImpairedMode", emit_null: true)]
  property enable_color_impaired_mode : Bool?

  @[JSON::Field(key: "theme", emit_null: true)]
  property theme : String?

  @[JSON::Field(key: "uiLanguage", emit_null: true)]
  property ui_language : Int32?
end
