# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::UnmappedFolder < Sonarr::Model
  @[JSON::Field(key: "name", emit_null: true)]
  property name : String?

  @[JSON::Field(key: "path", emit_null: true)]
  property path : String?

  @[JSON::Field(key: "relativePath", emit_null: true)]
  property relative_path : String?
end
