# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::UpdateChanges < Sonarr::Model
  @[JSON::Field(key: "new", emit_null: true)]
  property new = [] of String

  @[JSON::Field(key: "fixed", emit_null: true)]
  property fixed = [] of String
end
