# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::UpdateResource < Sonarr::Model
  @[JSON::Field(key: "id", emit_null: true)]
  property id : Int32?

  @[JSON::Field(key: "version", emit_null: true)]
  property version : String?

  @[JSON::Field(key: "branch", emit_null: true)]
  property branch : String?

  @[JSON::Field(key: "releaseDate", emit_null: true, converter: Sonarr::TimeConverter)]
  property release_date : Time?

  @[JSON::Field(key: "fileName", emit_null: true)]
  property file_name : String?

  @[JSON::Field(key: "url", emit_null: true)]
  property url : String?

  @[JSON::Field(key: "installed", emit_null: true)]
  property installed : Bool?

  @[JSON::Field(key: "installedOn", emit_null: true, converter: Sonarr::TimeConverter)]
  property installed_on : Time?

  @[JSON::Field(key: "installable", emit_null: true)]
  property installable : Bool?

  @[JSON::Field(key: "latest", emit_null: true)]
  property latest : Bool?

  @[JSON::Field(key: "changes", emit_null: true)]
  property changes : Sonarr::Model::UpdateChanges?

  @[JSON::Field(key: "hash", emit_null: true)]
  property hash : String?
end
