# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Model::UpdateChanges < Sonarr::Model
  @[JSON::Field(key: "new")]
  property new = [] of String

  @[JSON::Field(key: "fixed")]
  property fixed = [] of String
end
