# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::ApiInfo
  def initialize(@client : Sonarr::Client)
  end

  def list : Nil
    @client.request(:get, "/api")
  end
end
