# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::AutoTagging
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::AutoTaggingResource)
    @client.request_many(:get, "/api/v3/autotagging", Sonarr::Model::AutoTaggingResource)
  end

  def create(body : Sonarr::Model::AutoTaggingResource) : Sonarr::Model::AutoTaggingResource?
    @client.request_one(:post, "/api/v3/autotagging", Sonarr::Model::AutoTaggingResource, nil, body)
  end

  def list_schema : Nil
    @client.request(:get, "/api/v3/autotagging/schema")
  end

  def get(id : Int32) : Sonarr::Model::AutoTaggingResource?
    @client.request_one(:get, "/api/v3/autotagging/#{id}", Sonarr::Model::AutoTaggingResource)
  end

  def update(id : Int32, body : Sonarr::Model::AutoTaggingResource) : Sonarr::Model::AutoTaggingResource?
    @client.request_one(:put, "/api/v3/autotagging/#{id}", Sonarr::Model::AutoTaggingResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/autotagging/#{id}")
  end
end
