# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Blocklist
  def initialize(@client : Sonarr::Client)
  end

  def list(page : Int32? = nil, page_size : Int32? = nil, sort_key : String? = nil, sort_direction : Sonarr::SortDirection? = nil, series_ids : Array(Int32)? = nil, protocols : Array(Sonarr::DownloadProtocol)? = nil) : Sonarr::Model::BlocklistResourcePagingResource?
    query = Sonarr::Query.new
    query.add("page", page)
    query.add("pageSize", page_size)
    query.add("sortKey", sort_key)
    query.add("sortDirection", sort_direction)
    query.add("seriesIds", series_ids)
    query.add("protocols", protocols)
    @client.request_one(:get, "/api/v3/blocklist", Sonarr::Model::BlocklistResourcePagingResource, query)
  end

  def delete_bulk(body : Sonarr::Model::BlocklistBulkResource) : Nil
    @client.request(:delete, "/api/v3/blocklist/bulk", nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/blocklist/#{id}")
  end
end
