# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Calendar
  def initialize(@client : Sonarr::Client)
  end

  def list(start : Time? = nil, end_field : Time? = nil, unmonitored : Bool? = nil, include_series : Bool? = nil, include_episode_file : Bool? = nil, include_episode_images : Bool? = nil, tags : String? = nil) : Array(Sonarr::Model::EpisodeResource)
    query = Sonarr::Query.new
    query.add("start", start)
    query.add("end", end_field)
    query.add("unmonitored", unmonitored)
    query.add("includeSeries", include_series)
    query.add("includeEpisodeFile", include_episode_file)
    query.add("includeEpisodeImages", include_episode_images)
    query.add("tags", tags)
    @client.request_many(:get, "/api/v3/calendar", Sonarr::Model::EpisodeResource, query)
  end

  def get(id : Int32) : Sonarr::Model::EpisodeResource?
    @client.request_one(:get, "/api/v3/calendar/#{id}", Sonarr::Model::EpisodeResource)
  end
end
