# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Command
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::CommandResource)
    @client.request_many(:get, "/api/v3/command", Sonarr::Model::CommandResource)
  end

  def create(body : Sonarr::Model::CommandResource) : Sonarr::Model::CommandResource?
    @client.request_one(:post, "/api/v3/command", Sonarr::Model::CommandResource, nil, body)
  end

  def get(id : Int32) : Sonarr::Model::CommandResource?
    @client.request_one(:get, "/api/v3/command/#{id}", Sonarr::Model::CommandResource)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/command/#{id}")
  end
end
