# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::CustomFilter
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::CustomFilterResource)
    @client.request_many(:get, "/api/v3/customfilter", Sonarr::Model::CustomFilterResource)
  end

  def create(body : Sonarr::Model::CustomFilterResource) : Sonarr::Model::CustomFilterResource?
    @client.request_one(:post, "/api/v3/customfilter", Sonarr::Model::CustomFilterResource, nil, body)
  end

  def get(id : Int32) : Sonarr::Model::CustomFilterResource?
    @client.request_one(:get, "/api/v3/customfilter/#{id}", Sonarr::Model::CustomFilterResource)
  end

  def update(id : Int32, body : Sonarr::Model::CustomFilterResource) : Sonarr::Model::CustomFilterResource?
    @client.request_one(:put, "/api/v3/customfilter/#{id}", Sonarr::Model::CustomFilterResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/customfilter/#{id}")
  end
end
