# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::CustomFormat
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::CustomFormatResource)
    @client.request_many(:get, "/api/v3/customformat", Sonarr::Model::CustomFormatResource)
  end

  def create(body : Sonarr::Model::CustomFormatResource) : Sonarr::Model::CustomFormatResource?
    @client.request_one(:post, "/api/v3/customformat", Sonarr::Model::CustomFormatResource, nil, body)
  end

  def update_bulk(body : Sonarr::Model::CustomFormatBulkResource) : Sonarr::Model::CustomFormatResource?
    @client.request_one(:put, "/api/v3/customformat/bulk", Sonarr::Model::CustomFormatResource, nil, body)
  end

  def delete_bulk(body : Sonarr::Model::CustomFormatBulkResource) : Nil
    @client.request(:delete, "/api/v3/customformat/bulk", nil, body)
  end

  def list_schema : Nil
    @client.request(:get, "/api/v3/customformat/schema")
  end

  def get(id : Int32) : Sonarr::Model::CustomFormatResource?
    @client.request_one(:get, "/api/v3/customformat/#{id}", Sonarr::Model::CustomFormatResource)
  end

  def update(id : Int32, body : Sonarr::Model::CustomFormatResource) : Sonarr::Model::CustomFormatResource?
    @client.request_one(:put, "/api/v3/customformat/#{id}", Sonarr::Model::CustomFormatResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/customformat/#{id}")
  end
end
