# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Cutoff
  def initialize(@client : Sonarr::Client)
  end

  def list_cutoff(page : Int32? = nil, page_size : Int32? = nil, sort_key : String? = nil, sort_direction : Sonarr::SortDirection? = nil, include_series : Bool? = nil, include_episode_file : Bool? = nil, include_images : Bool? = nil, monitored : Bool? = nil) : Sonarr::Model::EpisodeResourcePagingResource?
    query = Sonarr::Query.new
    query.add("page", page)
    query.add("pageSize", page_size)
    query.add("sortKey", sort_key)
    query.add("sortDirection", sort_direction)
    query.add("includeSeries", include_series)
    query.add("includeEpisodeFile", include_episode_file)
    query.add("includeImages", include_images)
    query.add("monitored", monitored)
    @client.request_one(:get, "/api/v3/wanted/cutoff", Sonarr::Model::EpisodeResourcePagingResource, query)
  end

  def get_cutoff(id : Int32) : Sonarr::Model::EpisodeResource?
    @client.request_one(:get, "/api/v3/wanted/cutoff/#{id}", Sonarr::Model::EpisodeResource)
  end
end
