# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::DelayProfile
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::DelayProfileResource)
    @client.request_many(:get, "/api/v3/delayprofile", Sonarr::Model::DelayProfileResource)
  end

  def create(body : Sonarr::Model::DelayProfileResource) : Sonarr::Model::DelayProfileResource?
    @client.request_one(:post, "/api/v3/delayprofile", Sonarr::Model::DelayProfileResource, nil, body)
  end

  def update_reorder(id : Int32, after : Int32? = nil) : Array(Sonarr::Model::DelayProfileResource)
    query = Sonarr::Query.new
    query.add("after", after)
    @client.request_many(:put, "/api/v3/delayprofile/reorder/#{id}", Sonarr::Model::DelayProfileResource, query)
  end

  def get(id : Int32) : Sonarr::Model::DelayProfileResource?
    @client.request_one(:get, "/api/v3/delayprofile/#{id}", Sonarr::Model::DelayProfileResource)
  end

  def update(id : Int32, body : Sonarr::Model::DelayProfileResource) : Sonarr::Model::DelayProfileResource?
    @client.request_one(:put, "/api/v3/delayprofile/#{id}", Sonarr::Model::DelayProfileResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/delayprofile/#{id}")
  end
end
