# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::DiskSpace
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::DiskSpaceResource)
    @client.request_many(:get, "/api/v3/diskspace", Sonarr::Model::DiskSpaceResource)
  end
end
