# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::DownloadClientConfig
  def initialize(@client : Sonarr::Client)
  end

  def list_downloadclient : Sonarr::Model::DownloadClientConfigResource?
    @client.request_one(:get, "/api/v3/config/downloadclient", Sonarr::Model::DownloadClientConfigResource)
  end

  def get_downloadclient(id : Int32) : Sonarr::Model::DownloadClientConfigResource?
    @client.request_one(:get, "/api/v3/config/downloadclient/#{id}", Sonarr::Model::DownloadClientConfigResource)
  end

  def update_downloadclient(id : Int32, body : Sonarr::Model::DownloadClientConfigResource) : Sonarr::Model::DownloadClientConfigResource?
    @client.request_one(:put, "/api/v3/config/downloadclient/#{id}", Sonarr::Model::DownloadClientConfigResource, nil, body)
  end
end
