# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::DownloadClient
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::DownloadClientResource)
    @client.request_many(:get, "/api/v3/downloadclient", Sonarr::Model::DownloadClientResource)
  end

  def create(body : Sonarr::Model::DownloadClientResource, force_save : Bool? = nil) : Sonarr::Model::DownloadClientResource?
    query = Sonarr::Query.new
    query.add("forceSave", force_save)
    @client.request_one(:post, "/api/v3/downloadclient", Sonarr::Model::DownloadClientResource, query, body)
  end

  def create_action(name : String, body : Sonarr::Model::DownloadClientResource) : Nil
    @client.request(:post, "/api/v3/downloadclient/action/#{name}", nil, body)
  end

  def update_bulk(body : Sonarr::Model::DownloadClientBulkResource) : Sonarr::Model::DownloadClientResource?
    @client.request_one(:put, "/api/v3/downloadclient/bulk", Sonarr::Model::DownloadClientResource, nil, body)
  end

  def delete_bulk(body : Sonarr::Model::DownloadClientBulkResource) : Nil
    @client.request(:delete, "/api/v3/downloadclient/bulk", nil, body)
  end

  def list_schema : Array(Sonarr::Model::DownloadClientResource)
    @client.request_many(:get, "/api/v3/downloadclient/schema", Sonarr::Model::DownloadClientResource)
  end

  def create_test(body : Sonarr::Model::DownloadClientResource, force_test : Bool? = nil) : Nil
    query = Sonarr::Query.new
    query.add("forceTest", force_test)
    @client.request(:post, "/api/v3/downloadclient/test", query, body)
  end

  def create_testall : Nil
    @client.request(:post, "/api/v3/downloadclient/testall")
  end

  def get(id : Int32) : Sonarr::Model::DownloadClientResource?
    @client.request_one(:get, "/api/v3/downloadclient/#{id}", Sonarr::Model::DownloadClientResource)
  end

  def update(id : Int32, body : Sonarr::Model::DownloadClientResource, force_save : Bool? = nil) : Sonarr::Model::DownloadClientResource?
    query = Sonarr::Query.new
    query.add("forceSave", force_save)
    @client.request_one(:put, "/api/v3/downloadclient/#{id}", Sonarr::Model::DownloadClientResource, query, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/downloadclient/#{id}")
  end
end
