# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Episode
  def initialize(@client : Sonarr::Client)
  end

  def list(series_id : Int32? = nil, season_number : Int32? = nil, episode_ids : Array(Int32)? = nil, episode_file_id : Int32? = nil, include_series : Bool? = nil, include_episode_file : Bool? = nil, include_images : Bool? = nil) : Array(Sonarr::Model::EpisodeResource)
    query = Sonarr::Query.new
    query.add("seriesId", series_id)
    query.add("seasonNumber", season_number)
    query.add("episodeIds", episode_ids)
    query.add("episodeFileId", episode_file_id)
    query.add("includeSeries", include_series)
    query.add("includeEpisodeFile", include_episode_file)
    query.add("includeImages", include_images)
    @client.request_many(:get, "/api/v3/episode", Sonarr::Model::EpisodeResource, query)
  end

  def update_monitor(body : Sonarr::Model::EpisodesMonitoredResource, include_images : Bool? = nil) : Nil
    query = Sonarr::Query.new
    query.add("includeImages", include_images)
    @client.request(:put, "/api/v3/episode/monitor", query, body)
  end

  def get(id : Int32) : Sonarr::Model::EpisodeResource?
    @client.request_one(:get, "/api/v3/episode/#{id}", Sonarr::Model::EpisodeResource)
  end

  def update(id : Int32, body : Sonarr::Model::EpisodeResource) : Sonarr::Model::EpisodeResource?
    @client.request_one(:put, "/api/v3/episode/#{id}", Sonarr::Model::EpisodeResource, nil, body)
  end
end
