# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::EpisodeFile
  def initialize(@client : Sonarr::Client)
  end

  def list(series_id : Int32? = nil, episode_file_ids : Array(Int32)? = nil) : Array(Sonarr::Model::EpisodeFileResource)
    query = Sonarr::Query.new
    query.add("seriesId", series_id)
    query.add("episodeFileIds", episode_file_ids)
    @client.request_many(:get, "/api/v3/episodefile", Sonarr::Model::EpisodeFileResource, query)
  end

  def update_bulk(body : Array(Sonarr::Model::EpisodeFileResource)) : Nil
    @client.request(:put, "/api/v3/episodefile/bulk", nil, body)
  end

  def delete_bulk(body : Sonarr::Model::EpisodeFileListResource) : Nil
    @client.request(:delete, "/api/v3/episodefile/bulk", nil, body)
  end

  def update_editor(body : Sonarr::Model::EpisodeFileListResource) : Nil
    @client.request(:put, "/api/v3/episodefile/editor", nil, body)
  end

  def get(id : Int32) : Sonarr::Model::EpisodeFileResource?
    @client.request_one(:get, "/api/v3/episodefile/#{id}", Sonarr::Model::EpisodeFileResource)
  end

  def update(id : Int32, body : Sonarr::Model::EpisodeFileResource) : Sonarr::Model::EpisodeFileResource?
    @client.request_one(:put, "/api/v3/episodefile/#{id}", Sonarr::Model::EpisodeFileResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/episodefile/#{id}")
  end
end
