# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::FileSystem
  def initialize(@client : Sonarr::Client)
  end

  def list(path : String? = nil, include_files : Bool? = nil, allow_folders_without_trailing_slashes : Bool? = nil) : Nil
    query = Sonarr::Query.new
    query.add("path", path)
    query.add("includeFiles", include_files)
    query.add("allowFoldersWithoutTrailingSlashes", allow_folders_without_trailing_slashes)
    @client.request(:get, "/api/v3/filesystem", query)
  end

  def list_mediafiles(path : String? = nil) : Nil
    query = Sonarr::Query.new
    query.add("path", path)
    @client.request(:get, "/api/v3/filesystem/mediafiles", query)
  end

  def list_type(path : String? = nil) : Nil
    query = Sonarr::Query.new
    query.add("path", path)
    @client.request(:get, "/api/v3/filesystem/type", query)
  end
end
