# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Health
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::HealthResource)
    @client.request_many(:get, "/api/v3/health", Sonarr::Model::HealthResource)
  end
end
