# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::History
  def initialize(@client : Sonarr::Client)
  end

  def list(page : Int32? = nil, page_size : Int32? = nil, sort_key : String? = nil, sort_direction : Sonarr::SortDirection? = nil, include_series : Bool? = nil, include_episode : Bool? = nil, event_type : Array(Int32)? = nil, episode_id : Int32? = nil, download_id : String? = nil, series_ids : Array(Int32)? = nil, languages : Array(Int32)? = nil, quality : Array(Int32)? = nil) : Sonarr::Model::HistoryResourcePagingResource?
    query = Sonarr::Query.new
    query.add("page", page)
    query.add("pageSize", page_size)
    query.add("sortKey", sort_key)
    query.add("sortDirection", sort_direction)
    query.add("includeSeries", include_series)
    query.add("includeEpisode", include_episode)
    query.add("eventType", event_type)
    query.add("episodeId", episode_id)
    query.add("downloadId", download_id)
    query.add("seriesIds", series_ids)
    query.add("languages", languages)
    query.add("quality", quality)
    @client.request_one(:get, "/api/v3/history", Sonarr::Model::HistoryResourcePagingResource, query)
  end

  def create_failed(id : Int32) : Nil
    @client.request(:post, "/api/v3/history/failed/#{id}")
  end

  def get_series(series_id : Int32? = nil, season_number : Int32? = nil, event_type : Sonarr::EpisodeHistoryEventType? = nil, include_series : Bool? = nil, include_episode : Bool? = nil) : Array(Sonarr::Model::HistoryResource)
    query = Sonarr::Query.new
    query.add("seriesId", series_id)
    query.add("seasonNumber", season_number)
    query.add("eventType", event_type)
    query.add("includeSeries", include_series)
    query.add("includeEpisode", include_episode)
    @client.request_many(:get, "/api/v3/history/series", Sonarr::Model::HistoryResource, query)
  end

  def get_since(date : Time? = nil, event_type : Sonarr::EpisodeHistoryEventType? = nil, include_series : Bool? = nil, include_episode : Bool? = nil) : Array(Sonarr::Model::HistoryResource)
    query = Sonarr::Query.new
    query.add("date", date)
    query.add("eventType", event_type)
    query.add("includeSeries", include_series)
    query.add("includeEpisode", include_episode)
    @client.request_many(:get, "/api/v3/history/since", Sonarr::Model::HistoryResource, query)
  end
end
