# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::HostConfig
  def initialize(@client : Sonarr::Client)
  end

  def list_host : Sonarr::Model::HostConfigResource?
    @client.request_one(:get, "/api/v3/config/host", Sonarr::Model::HostConfigResource)
  end

  def get_host(id : Int32) : Sonarr::Model::HostConfigResource?
    @client.request_one(:get, "/api/v3/config/host/#{id}", Sonarr::Model::HostConfigResource)
  end

  def update_host(id : Int32, body : Sonarr::Model::HostConfigResource) : Sonarr::Model::HostConfigResource?
    @client.request_one(:put, "/api/v3/config/host/#{id}", Sonarr::Model::HostConfigResource, nil, body)
  end
end
