# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::ImportListConfig
  def initialize(@client : Sonarr::Client)
  end

  def list_importlist : Sonarr::Model::ImportListConfigResource?
    @client.request_one(:get, "/api/v3/config/importlist", Sonarr::Model::ImportListConfigResource)
  end

  def get_importlist(id : Int32) : Sonarr::Model::ImportListConfigResource?
    @client.request_one(:get, "/api/v3/config/importlist/#{id}", Sonarr::Model::ImportListConfigResource)
  end

  def update_importlist(id : Int32, body : Sonarr::Model::ImportListConfigResource) : Sonarr::Model::ImportListConfigResource?
    @client.request_one(:put, "/api/v3/config/importlist/#{id}", Sonarr::Model::ImportListConfigResource, nil, body)
  end
end
