# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::ImportListExclusion
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::ImportListExclusionResource)
    @client.request_many(:get, "/api/v3/importlistexclusion", Sonarr::Model::ImportListExclusionResource)
  end

  def create(body : Sonarr::Model::ImportListExclusionResource) : Sonarr::Model::ImportListExclusionResource?
    @client.request_one(:post, "/api/v3/importlistexclusion", Sonarr::Model::ImportListExclusionResource, nil, body)
  end

  def delete_bulk(body : Sonarr::Model::ImportListExclusionBulkResource) : Nil
    @client.request(:delete, "/api/v3/importlistexclusion/bulk", nil, body)
  end

  def list_paged(page : Int32? = nil, page_size : Int32? = nil, sort_key : String? = nil, sort_direction : Sonarr::SortDirection? = nil) : Sonarr::Model::ImportListExclusionResourcePagingResource?
    query = Sonarr::Query.new
    query.add("page", page)
    query.add("pageSize", page_size)
    query.add("sortKey", sort_key)
    query.add("sortDirection", sort_direction)
    @client.request_one(:get, "/api/v3/importlistexclusion/paged", Sonarr::Model::ImportListExclusionResourcePagingResource, query)
  end

  def get(id : Int32) : Sonarr::Model::ImportListExclusionResource?
    @client.request_one(:get, "/api/v3/importlistexclusion/#{id}", Sonarr::Model::ImportListExclusionResource)
  end

  def update(id : Int32, body : Sonarr::Model::ImportListExclusionResource) : Sonarr::Model::ImportListExclusionResource?
    @client.request_one(:put, "/api/v3/importlistexclusion/#{id}", Sonarr::Model::ImportListExclusionResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/importlistexclusion/#{id}")
  end
end
