# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::ImportList
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::ImportListResource)
    @client.request_many(:get, "/api/v3/importlist", Sonarr::Model::ImportListResource)
  end

  def create(body : Sonarr::Model::ImportListResource, force_save : Bool? = nil) : Sonarr::Model::ImportListResource?
    query = Sonarr::Query.new
    query.add("forceSave", force_save)
    @client.request_one(:post, "/api/v3/importlist", Sonarr::Model::ImportListResource, query, body)
  end

  def create_action(name : String, body : Sonarr::Model::ImportListResource) : Nil
    @client.request(:post, "/api/v3/importlist/action/#{name}", nil, body)
  end

  def update_bulk(body : Sonarr::Model::ImportListBulkResource) : Sonarr::Model::ImportListResource?
    @client.request_one(:put, "/api/v3/importlist/bulk", Sonarr::Model::ImportListResource, nil, body)
  end

  def delete_bulk(body : Sonarr::Model::ImportListBulkResource) : Nil
    @client.request(:delete, "/api/v3/importlist/bulk", nil, body)
  end

  def list_schema : Array(Sonarr::Model::ImportListResource)
    @client.request_many(:get, "/api/v3/importlist/schema", Sonarr::Model::ImportListResource)
  end

  def create_test(body : Sonarr::Model::ImportListResource, force_test : Bool? = nil) : Nil
    query = Sonarr::Query.new
    query.add("forceTest", force_test)
    @client.request(:post, "/api/v3/importlist/test", query, body)
  end

  def create_testall : Nil
    @client.request(:post, "/api/v3/importlist/testall")
  end

  def get(id : Int32) : Sonarr::Model::ImportListResource?
    @client.request_one(:get, "/api/v3/importlist/#{id}", Sonarr::Model::ImportListResource)
  end

  def update(id : Int32, body : Sonarr::Model::ImportListResource, force_save : Bool? = nil) : Sonarr::Model::ImportListResource?
    query = Sonarr::Query.new
    query.add("forceSave", force_save)
    @client.request_one(:put, "/api/v3/importlist/#{id}", Sonarr::Model::ImportListResource, query, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/importlist/#{id}")
  end
end
