# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::IndexerConfig
  def initialize(@client : Sonarr::Client)
  end

  def list_indexer : Sonarr::Model::IndexerConfigResource?
    @client.request_one(:get, "/api/v3/config/indexer", Sonarr::Model::IndexerConfigResource)
  end

  def get_indexer(id : Int32) : Sonarr::Model::IndexerConfigResource?
    @client.request_one(:get, "/api/v3/config/indexer/#{id}", Sonarr::Model::IndexerConfigResource)
  end

  def update_indexer(id : Int32, body : Sonarr::Model::IndexerConfigResource) : Sonarr::Model::IndexerConfigResource?
    @client.request_one(:put, "/api/v3/config/indexer/#{id}", Sonarr::Model::IndexerConfigResource, nil, body)
  end
end
