# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::IndexerFlag
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::IndexerFlagResource)
    @client.request_many(:get, "/api/v3/indexerflag", Sonarr::Model::IndexerFlagResource)
  end
end
