# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::LanguageProfileSchema
  def initialize(@client : Sonarr::Client)
  end

  def list_schema : Sonarr::Model::LanguageProfileResource?
    @client.request_one(:get, "/api/v3/languageprofile/schema", Sonarr::Model::LanguageProfileResource)
  end
end
