# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::LanguageProfile
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::LanguageProfileResource)
    @client.request_many(:get, "/api/v3/languageprofile", Sonarr::Model::LanguageProfileResource)
  end

  def create(body : Sonarr::Model::LanguageProfileResource) : Sonarr::Model::LanguageProfileResource?
    @client.request_one(:post, "/api/v3/languageprofile", Sonarr::Model::LanguageProfileResource, nil, body)
  end

  def get(id : Int32) : Sonarr::Model::LanguageProfileResource?
    @client.request_one(:get, "/api/v3/languageprofile/#{id}", Sonarr::Model::LanguageProfileResource)
  end

  def update(id : Int32, body : Sonarr::Model::LanguageProfileResource) : Sonarr::Model::LanguageProfileResource?
    @client.request_one(:put, "/api/v3/languageprofile/#{id}", Sonarr::Model::LanguageProfileResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/languageprofile/#{id}")
  end
end
