# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Language
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::LanguageResource)
    @client.request_many(:get, "/api/v3/language", Sonarr::Model::LanguageResource)
  end

  def get(id : Int32) : Sonarr::Model::LanguageResource?
    @client.request_one(:get, "/api/v3/language/#{id}", Sonarr::Model::LanguageResource)
  end
end
