# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Localization
  def initialize(@client : Sonarr::Client)
  end

  def list : Sonarr::Model::LocalizationResource?
    @client.request_one(:get, "/api/v3/localization", Sonarr::Model::LocalizationResource)
  end

  def list_language : Sonarr::Model::LocalizationLanguageResource?
    @client.request_one(:get, "/api/v3/localization/language", Sonarr::Model::LocalizationLanguageResource)
  end

  def get(id : Int32) : Sonarr::Model::LocalizationResource?
    @client.request_one(:get, "/api/v3/localization/#{id}", Sonarr::Model::LocalizationResource)
  end
end
