# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Log
  def initialize(@client : Sonarr::Client)
  end

  def list(page : Int32? = nil, page_size : Int32? = nil, sort_key : String? = nil, sort_direction : Sonarr::SortDirection? = nil, level : String? = nil) : Sonarr::Model::LogResourcePagingResource?
    query = Sonarr::Query.new
    query.add("page", page)
    query.add("pageSize", page_size)
    query.add("sortKey", sort_key)
    query.add("sortDirection", sort_direction)
    query.add("level", level)
    @client.request_one(:get, "/api/v3/log", Sonarr::Model::LogResourcePagingResource, query)
  end
end
