# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::ManualImport
  def initialize(@client : Sonarr::Client)
  end

  def list(folder : String? = nil, download_id : String? = nil, series_id : Int32? = nil, season_number : Int32? = nil, filter_existing_files : Bool? = nil) : Array(Sonarr::Model::ManualImportResource)
    query = Sonarr::Query.new
    query.add("folder", folder)
    query.add("downloadId", download_id)
    query.add("seriesId", series_id)
    query.add("seasonNumber", season_number)
    query.add("filterExistingFiles", filter_existing_files)
    @client.request_many(:get, "/api/v3/manualimport", Sonarr::Model::ManualImportResource, query)
  end

  def create(body : Array(Sonarr::Model::ManualImportReprocessResource)) : Nil
    @client.request(:post, "/api/v3/manualimport", nil, body)
  end
end
