# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::MediaManagementConfig
  def initialize(@client : Sonarr::Client)
  end

  def list_mediamanagement : Sonarr::Model::MediaManagementConfigResource?
    @client.request_one(:get, "/api/v3/config/mediamanagement", Sonarr::Model::MediaManagementConfigResource)
  end

  def get_mediamanagement(id : Int32) : Sonarr::Model::MediaManagementConfigResource?
    @client.request_one(:get, "/api/v3/config/mediamanagement/#{id}", Sonarr::Model::MediaManagementConfigResource)
  end

  def update_mediamanagement(id : Int32, body : Sonarr::Model::MediaManagementConfigResource) : Sonarr::Model::MediaManagementConfigResource?
    @client.request_one(:put, "/api/v3/config/mediamanagement/#{id}", Sonarr::Model::MediaManagementConfigResource, nil, body)
  end
end
