# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::NamingConfig
  def initialize(@client : Sonarr::Client)
  end

  def list_naming : Sonarr::Model::NamingConfigResource?
    @client.request_one(:get, "/api/v3/config/naming", Sonarr::Model::NamingConfigResource)
  end

  def list_naming_examples(rename_episodes : Bool? = nil, replace_illegal_characters : Bool? = nil, colon_replacement_format : Int32? = nil, custom_colon_replacement_format : String? = nil, multi_episode_style : Int32? = nil, standard_episode_format : String? = nil, daily_episode_format : String? = nil, anime_episode_format : String? = nil, series_folder_format : String? = nil, season_folder_format : String? = nil, specials_folder_format : String? = nil, id : Int32? = nil, resource_name : String? = nil) : Nil
    query = Sonarr::Query.new
    query.add("renameEpisodes", rename_episodes)
    query.add("replaceIllegalCharacters", replace_illegal_characters)
    query.add("colonReplacementFormat", colon_replacement_format)
    query.add("customColonReplacementFormat", custom_colon_replacement_format)
    query.add("multiEpisodeStyle", multi_episode_style)
    query.add("standardEpisodeFormat", standard_episode_format)
    query.add("dailyEpisodeFormat", daily_episode_format)
    query.add("animeEpisodeFormat", anime_episode_format)
    query.add("seriesFolderFormat", series_folder_format)
    query.add("seasonFolderFormat", season_folder_format)
    query.add("specialsFolderFormat", specials_folder_format)
    query.add("id", id)
    query.add("resourceName", resource_name)
    @client.request(:get, "/api/v3/config/naming/examples", query)
  end

  def get_naming(id : Int32) : Sonarr::Model::NamingConfigResource?
    @client.request_one(:get, "/api/v3/config/naming/#{id}", Sonarr::Model::NamingConfigResource)
  end

  def update_naming(id : Int32, body : Sonarr::Model::NamingConfigResource) : Sonarr::Model::NamingConfigResource?
    @client.request_one(:put, "/api/v3/config/naming/#{id}", Sonarr::Model::NamingConfigResource, nil, body)
  end
end
