# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Notification
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::NotificationResource)
    @client.request_many(:get, "/api/v3/notification", Sonarr::Model::NotificationResource)
  end

  def create(body : Sonarr::Model::NotificationResource, force_save : Bool? = nil) : Sonarr::Model::NotificationResource?
    query = Sonarr::Query.new
    query.add("forceSave", force_save)
    @client.request_one(:post, "/api/v3/notification", Sonarr::Model::NotificationResource, query, body)
  end

  def create_action(name : String, body : Sonarr::Model::NotificationResource) : Nil
    @client.request(:post, "/api/v3/notification/action/#{name}", nil, body)
  end

  def list_schema : Array(Sonarr::Model::NotificationResource)
    @client.request_many(:get, "/api/v3/notification/schema", Sonarr::Model::NotificationResource)
  end

  def create_test(body : Sonarr::Model::NotificationResource, force_test : Bool? = nil) : Nil
    query = Sonarr::Query.new
    query.add("forceTest", force_test)
    @client.request(:post, "/api/v3/notification/test", query, body)
  end

  def create_testall : Nil
    @client.request(:post, "/api/v3/notification/testall")
  end

  def get(id : Int32) : Sonarr::Model::NotificationResource?
    @client.request_one(:get, "/api/v3/notification/#{id}", Sonarr::Model::NotificationResource)
  end

  def update(id : Int32, body : Sonarr::Model::NotificationResource, force_save : Bool? = nil) : Sonarr::Model::NotificationResource?
    query = Sonarr::Query.new
    query.add("forceSave", force_save)
    @client.request_one(:put, "/api/v3/notification/#{id}", Sonarr::Model::NotificationResource, query, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/notification/#{id}")
  end
end
