# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Parse
  def initialize(@client : Sonarr::Client)
  end

  def list(title : String? = nil, path : String? = nil) : Sonarr::Model::ParseResource?
    query = Sonarr::Query.new
    query.add("title", title)
    query.add("path", path)
    @client.request_one(:get, "/api/v3/parse", Sonarr::Model::ParseResource, query)
  end
end
