# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Ping
  def initialize(@client : Sonarr::Client)
  end

  def list : Sonarr::Model::PingResource?
    @client.request_one(:get, "/ping", Sonarr::Model::PingResource)
  end
end
