# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::QualityDefinition
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::QualityDefinitionResource)
    @client.request_many(:get, "/api/v3/qualitydefinition", Sonarr::Model::QualityDefinitionResource)
  end

  def list_limits : Sonarr::Model::QualityDefinitionLimitsResource?
    @client.request_one(:get, "/api/v3/qualitydefinition/limits", Sonarr::Model::QualityDefinitionLimitsResource)
  end

  def update_update(body : Array(Sonarr::Model::QualityDefinitionResource)) : Nil
    @client.request(:put, "/api/v3/qualitydefinition/update", nil, body)
  end

  def get(id : Int32) : Sonarr::Model::QualityDefinitionResource?
    @client.request_one(:get, "/api/v3/qualitydefinition/#{id}", Sonarr::Model::QualityDefinitionResource)
  end

  def update(id : Int32, body : Sonarr::Model::QualityDefinitionResource) : Sonarr::Model::QualityDefinitionResource?
    @client.request_one(:put, "/api/v3/qualitydefinition/#{id}", Sonarr::Model::QualityDefinitionResource, nil, body)
  end
end
