# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::QualityProfile
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::QualityProfileResource)
    @client.request_many(:get, "/api/v3/qualityprofile", Sonarr::Model::QualityProfileResource)
  end

  def create(body : Sonarr::Model::QualityProfileResource) : Sonarr::Model::QualityProfileResource?
    @client.request_one(:post, "/api/v3/qualityprofile", Sonarr::Model::QualityProfileResource, nil, body)
  end

  def get(id : Int32) : Sonarr::Model::QualityProfileResource?
    @client.request_one(:get, "/api/v3/qualityprofile/#{id}", Sonarr::Model::QualityProfileResource)
  end

  def update(id : Int32, body : Sonarr::Model::QualityProfileResource) : Sonarr::Model::QualityProfileResource?
    @client.request_one(:put, "/api/v3/qualityprofile/#{id}", Sonarr::Model::QualityProfileResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/qualityprofile/#{id}")
  end
end
