# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::QualityProfileSchema
  def initialize(@client : Sonarr::Client)
  end

  def list_schema : Sonarr::Model::QualityProfileResource?
    @client.request_one(:get, "/api/v3/qualityprofile/schema", Sonarr::Model::QualityProfileResource)
  end
end
