# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::QueueStatus
  def initialize(@client : Sonarr::Client)
  end

  def list_status : Sonarr::Model::QueueStatusResource?
    @client.request_one(:get, "/api/v3/queue/status", Sonarr::Model::QueueStatusResource)
  end
end
