# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Queue
  def initialize(@client : Sonarr::Client)
  end

  def list(page : Int32? = nil, page_size : Int32? = nil, sort_key : String? = nil, sort_direction : Sonarr::SortDirection? = nil, include_unknown_series_items : Bool? = nil, include_series : Bool? = nil, include_episode : Bool? = nil, series_ids : Array(Int32)? = nil, protocol : Sonarr::DownloadProtocol? = nil, languages : Array(Int32)? = nil, quality : Array(Int32)? = nil, status : Array(Sonarr::QueueStatus)? = nil) : Sonarr::Model::QueueResourcePagingResource?
    query = Sonarr::Query.new
    query.add("page", page)
    query.add("pageSize", page_size)
    query.add("sortKey", sort_key)
    query.add("sortDirection", sort_direction)
    query.add("includeUnknownSeriesItems", include_unknown_series_items)
    query.add("includeSeries", include_series)
    query.add("includeEpisode", include_episode)
    query.add("seriesIds", series_ids)
    query.add("protocol", protocol)
    query.add("languages", languages)
    query.add("quality", quality)
    query.add("status", status)
    @client.request_one(:get, "/api/v3/queue", Sonarr::Model::QueueResourcePagingResource, query)
  end

  def delete_bulk(body : Sonarr::Model::QueueBulkResource, remove_from_client : Bool? = nil, blocklist : Bool? = nil, skip_redownload : Bool? = nil, change_category : Bool? = nil) : Nil
    query = Sonarr::Query.new
    query.add("removeFromClient", remove_from_client)
    query.add("blocklist", blocklist)
    query.add("skipRedownload", skip_redownload)
    query.add("changeCategory", change_category)
    @client.request(:delete, "/api/v3/queue/bulk", query, body)
  end

  def delete(id : Int32, remove_from_client : Bool? = nil, blocklist : Bool? = nil, skip_redownload : Bool? = nil, change_category : Bool? = nil) : Nil
    query = Sonarr::Query.new
    query.add("removeFromClient", remove_from_client)
    query.add("blocklist", blocklist)
    query.add("skipRedownload", skip_redownload)
    query.add("changeCategory", change_category)
    @client.request(:delete, "/api/v3/queue/#{id}", query)
  end
end
