# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::QueueDetails
  def initialize(@client : Sonarr::Client)
  end

  def list_details(series_id : Int32? = nil, episode_ids : Array(Int32)? = nil, include_series : Bool? = nil, include_episode : Bool? = nil) : Array(Sonarr::Model::QueueResource)
    query = Sonarr::Query.new
    query.add("seriesId", series_id)
    query.add("episodeIds", episode_ids)
    query.add("includeSeries", include_series)
    query.add("includeEpisode", include_episode)
    @client.request_many(:get, "/api/v3/queue/details", Sonarr::Model::QueueResource, query)
  end
end
