# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::ReleaseProfile
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::ReleaseProfileResource)
    @client.request_many(:get, "/api/v3/releaseprofile", Sonarr::Model::ReleaseProfileResource)
  end

  def create(body : Sonarr::Model::ReleaseProfileResource) : Sonarr::Model::ReleaseProfileResource?
    @client.request_one(:post, "/api/v3/releaseprofile", Sonarr::Model::ReleaseProfileResource, nil, body)
  end

  def get(id : Int32) : Sonarr::Model::ReleaseProfileResource?
    @client.request_one(:get, "/api/v3/releaseprofile/#{id}", Sonarr::Model::ReleaseProfileResource)
  end

  def update(id : Int32, body : Sonarr::Model::ReleaseProfileResource) : Sonarr::Model::ReleaseProfileResource?
    @client.request_one(:put, "/api/v3/releaseprofile/#{id}", Sonarr::Model::ReleaseProfileResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/releaseprofile/#{id}")
  end
end
