# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Release
  def initialize(@client : Sonarr::Client)
  end

  def list(series_id : Int32? = nil, episode_id : Int32? = nil, season_number : Int32? = nil) : Array(Sonarr::Model::ReleaseResource)
    query = Sonarr::Query.new
    query.add("seriesId", series_id)
    query.add("episodeId", episode_id)
    query.add("seasonNumber", season_number)
    @client.request_many(:get, "/api/v3/release", Sonarr::Model::ReleaseResource, query)
  end

  def create(body : Sonarr::Model::ReleaseResource) : Nil
    @client.request(:post, "/api/v3/release", nil, body)
  end
end
