# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::ReleasePush
  def initialize(@client : Sonarr::Client)
  end

  def create_push(body : Sonarr::Model::ReleaseResource) : Array(Sonarr::Model::ReleaseResource)
    @client.request_many(:post, "/api/v3/release/push", Sonarr::Model::ReleaseResource, nil, body)
  end
end
