# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::RemotePathMapping
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::RemotePathMappingResource)
    @client.request_many(:get, "/api/v3/remotepathmapping", Sonarr::Model::RemotePathMappingResource)
  end

  def create(body : Sonarr::Model::RemotePathMappingResource) : Sonarr::Model::RemotePathMappingResource?
    @client.request_one(:post, "/api/v3/remotepathmapping", Sonarr::Model::RemotePathMappingResource, nil, body)
  end

  def get(id : Int32) : Sonarr::Model::RemotePathMappingResource?
    @client.request_one(:get, "/api/v3/remotepathmapping/#{id}", Sonarr::Model::RemotePathMappingResource)
  end

  def update(id : Int32, body : Sonarr::Model::RemotePathMappingResource) : Sonarr::Model::RemotePathMappingResource?
    @client.request_one(:put, "/api/v3/remotepathmapping/#{id}", Sonarr::Model::RemotePathMappingResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/remotepathmapping/#{id}")
  end
end
