# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::RenameEpisode
  def initialize(@client : Sonarr::Client)
  end

  def list(series_id : Int32? = nil, season_number : Int32? = nil) : Array(Sonarr::Model::RenameEpisodeResource)
    query = Sonarr::Query.new
    query.add("seriesId", series_id)
    query.add("seasonNumber", season_number)
    @client.request_many(:get, "/api/v3/rename", Sonarr::Model::RenameEpisodeResource, query)
  end
end
