# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::RootFolder
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::RootFolderResource)
    @client.request_many(:get, "/api/v3/rootfolder", Sonarr::Model::RootFolderResource)
  end

  def create(body : Sonarr::Model::RootFolderResource) : Sonarr::Model::RootFolderResource?
    @client.request_one(:post, "/api/v3/rootfolder", Sonarr::Model::RootFolderResource, nil, body)
  end

  def get(id : Int32) : Sonarr::Model::RootFolderResource?
    @client.request_one(:get, "/api/v3/rootfolder/#{id}", Sonarr::Model::RootFolderResource)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/rootfolder/#{id}")
  end
end
