# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::SeasonPass
  def initialize(@client : Sonarr::Client)
  end

  def create(body : Sonarr::Model::SeasonPassResource) : Nil
    @client.request(:post, "/api/v3/seasonpass", nil, body)
  end
end
