# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::SeriesFolder
  def initialize(@client : Sonarr::Client)
  end

  def list_folder(id : Int32) : Nil
    @client.request(:get, "/api/v3/series/#{id}/folder")
  end
end
