# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::SeriesLookup
  def initialize(@client : Sonarr::Client)
  end

  def list_lookup(term : String? = nil) : Array(Sonarr::Model::SeriesResource)
    query = Sonarr::Query.new
    query.add("term", term)
    @client.request_many(:get, "/api/v3/series/lookup", Sonarr::Model::SeriesResource, query)
  end
end
