# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Series
  def initialize(@client : Sonarr::Client)
  end

  def list(tvdb_id : Int32? = nil, include_season_images : Bool? = nil) : Array(Sonarr::Model::SeriesResource)
    query = Sonarr::Query.new
    query.add("tvdbId", tvdb_id)
    query.add("includeSeasonImages", include_season_images)
    @client.request_many(:get, "/api/v3/series", Sonarr::Model::SeriesResource, query)
  end

  def create(body : Sonarr::Model::SeriesResource) : Sonarr::Model::SeriesResource?
    @client.request_one(:post, "/api/v3/series", Sonarr::Model::SeriesResource, nil, body)
  end

  def get(id : Int32, include_season_images : Bool? = nil) : Sonarr::Model::SeriesResource?
    query = Sonarr::Query.new
    query.add("includeSeasonImages", include_season_images)
    @client.request_one(:get, "/api/v3/series/#{id}", Sonarr::Model::SeriesResource, query)
  end

  def update(id : Int32, body : Sonarr::Model::SeriesResource, move_files : Bool? = nil) : Sonarr::Model::SeriesResource?
    query = Sonarr::Query.new
    query.add("moveFiles", move_files)
    @client.request_one(:put, "/api/v3/series/#{id}", Sonarr::Model::SeriesResource, query, body)
  end

  def delete(id : Int32, delete_files : Bool? = nil, add_import_list_exclusion : Bool? = nil) : Nil
    query = Sonarr::Query.new
    query.add("deleteFiles", delete_files)
    query.add("addImportListExclusion", add_import_list_exclusion)
    @client.request(:delete, "/api/v3/series/#{id}", query)
  end
end
