# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::SeriesImport
  def initialize(@client : Sonarr::Client)
  end

  def create_import(body : Array(Sonarr::Model::SeriesResource)) : Nil
    @client.request(:post, "/api/v3/series/import", nil, body)
  end
end
