# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::SeriesEditor
  def initialize(@client : Sonarr::Client)
  end

  def update_editor(body : Sonarr::Model::SeriesEditorResource) : Nil
    @client.request(:put, "/api/v3/series/editor", nil, body)
  end

  def delete_editor(body : Sonarr::Model::SeriesEditorResource) : Nil
    @client.request(:delete, "/api/v3/series/editor", nil, body)
  end
end
