# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::System
  def initialize(@client : Sonarr::Client)
  end

  def create_restart : Nil
    @client.request(:post, "/api/v3/system/restart")
  end

  def list_routes : Nil
    @client.request(:get, "/api/v3/system/routes")
  end

  def list_routes_duplicate : Nil
    @client.request(:get, "/api/v3/system/routes/duplicate")
  end

  def create_shutdown : Nil
    @client.request(:post, "/api/v3/system/shutdown")
  end

  def list_status : Sonarr::Model::SystemResource?
    @client.request_one(:get, "/api/v3/system/status", Sonarr::Model::SystemResource)
  end
end
