# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Tag
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::TagResource)
    @client.request_many(:get, "/api/v3/tag", Sonarr::Model::TagResource)
  end

  def create(body : Sonarr::Model::TagResource) : Sonarr::Model::TagResource?
    @client.request_one(:post, "/api/v3/tag", Sonarr::Model::TagResource, nil, body)
  end

  def get(id : Int32) : Sonarr::Model::TagResource?
    @client.request_one(:get, "/api/v3/tag/#{id}", Sonarr::Model::TagResource)
  end

  def update(id : Int32, body : Sonarr::Model::TagResource) : Sonarr::Model::TagResource?
    @client.request_one(:put, "/api/v3/tag/#{id}", Sonarr::Model::TagResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/tag/#{id}")
  end
end
