# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::TagDetails
  def initialize(@client : Sonarr::Client)
  end

  def list_detail : Array(Sonarr::Model::TagDetailsResource)
    @client.request_many(:get, "/api/v3/tag/detail", Sonarr::Model::TagDetailsResource)
  end

  def get_detail(id : Int32) : Sonarr::Model::TagDetailsResource?
    @client.request_one(:get, "/api/v3/tag/detail/#{id}", Sonarr::Model::TagDetailsResource)
  end
end
