# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Task
  def initialize(@client : Sonarr::Client)
  end

  def list_task : Array(Sonarr::Model::TaskResource)
    @client.request_many(:get, "/api/v3/system/task", Sonarr::Model::TaskResource)
  end

  def get_task(id : Int32) : Sonarr::Model::TaskResource?
    @client.request_one(:get, "/api/v3/system/task/#{id}", Sonarr::Model::TaskResource)
  end
end
