# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::UiConfig
  def initialize(@client : Sonarr::Client)
  end

  def list_ui : Sonarr::Model::UiConfigResource?
    @client.request_one(:get, "/api/v3/config/ui", Sonarr::Model::UiConfigResource)
  end

  def get_ui(id : Int32) : Sonarr::Model::UiConfigResource?
    @client.request_one(:get, "/api/v3/config/ui/#{id}", Sonarr::Model::UiConfigResource)
  end

  def update_ui(id : Int32, body : Sonarr::Model::UiConfigResource) : Sonarr::Model::UiConfigResource?
    @client.request_one(:put, "/api/v3/config/ui/#{id}", Sonarr::Model::UiConfigResource, nil, body)
  end
end
