# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::UpdateLogFile
  def initialize(@client : Sonarr::Client)
  end

  def list_file_update : Array(Sonarr::Model::LogFileResource)
    @client.request_many(:get, "/api/v3/log/file/update", Sonarr::Model::LogFileResource)
  end

  def get_file_update(filename : String) : Nil
    @client.request(:get, "/api/v3/log/file/update/#{filename}")
  end
end
