# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Sonarr::Api::Update
  def initialize(@client : Sonarr::Client)
  end

  def list : Array(Sonarr::Model::UpdateResource)
    @client.request_many(:get, "/api/v3/update", Sonarr::Model::UpdateResource)
  end
end
