# Schema-driven code generator for the `sonarr` shard.
#
# Reads `ext/schema.json` (Sonarr OpenAPI 3.0.0) and (re)writes:
#   * `src/sonarr/model/<snake_name>.cr` — one class per object schema
#   * `src/sonarr/support_enums.cr`      — all enum schemas
#
# Run with: `crystal run tools/generate.cr`
# Output is deterministic and idempotent (running twice yields no git diff).

require "json"
require "file_utils"

module Generator
  ROOT        = Path[__DIR__].parent
  SCHEMA_PATH = ROOT / "ext" / "schema.json"
  MODEL_DIR   = ROOT / "src" / "sonarr" / "model"
  ENUMS_PATH  = ROOT / "src" / "sonarr" / "support_enums.cr"

  HEADER = <<-HEADER
    # AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
    # Regenerate via: crystal run tools/generate.cr
    HEADER

  # Crystal hard keywords that cannot be used as bare identifiers.
  RESERVED = %w[
    abstract alias as asm begin break case class def do else elsif end ensure
    enum extend false for fun if in include instance_sizeof is_a lib macro
    module next nil of out pointerof private protected require rescue return
    select self sizeof struct super then true type typeof uninitialized union
    unless until when while with yield
  ]

  class Schema
    getter enums : Hash(String, JSON::Any)
    getter objects : Hash(String, JSON::Any)

    def initialize(path : Path)
      doc = JSON.parse(File.read(path))
      schemas = doc["components"]["schemas"].as_h
      @enums = {} of String => JSON::Any
      @objects = {} of String => JSON::Any
      schemas.each do |name, node|
        if node.as_h.has_key?("enum")
          @enums[name] = node
        else
          @objects[name] = node
        end
      end
    end

    def enum?(name : String) : Bool
      @enums.has_key?(name)
    end
  end

  # ---- naming helpers -------------------------------------------------------

  def self.snake_case(name : String) : String
    s = name.gsub(/([A-Z]+)([A-Z][a-z])/, "\\1_\\2")
    s = s.gsub(/([a-z0-9])([A-Z])/, "\\1_\\2")
    s.downcase
  end

  # PascalCase enum member name derived from its (camelCase) schema value.
  def self.member_name(value : String) : String
    value[0].upcase + value[1..]
  end

  # Snake-cased, keyword-safe Crystal property name for a JSON key.
  def self.property_name(key : String) : String
    name = snake_case(key)
    name = "digit_#{name}" if name[0]?.try &.ascii_number?
    name = "#{name}_field" if RESERVED.includes?(name)
    name
  end

  # ---- type resolution ------------------------------------------------------

  # Resolved Crystal type for a property, plus how it should be declared.
  record Resolved,
    expr : String,
    array : Bool = false,
    time : Bool = false

  def self.resolve(schema : Schema, node : JSON::Any) : Resolved
    h = node.as_h

    if ref = h["$ref"]?
      return Resolved.new(ref_type(schema, ref.as_s))
    end

    type = h["type"]?.try(&.as_s)
    case type
    when "array"
      Resolved.new("Array(#{value_expr(schema, h["items"])})", array: true)
    when "object"
      Resolved.new(hash_type(schema, h["additionalProperties"]?))
    when "string"
      case h["format"]?.try(&.as_s)
      when "date-time"
        Resolved.new("Time", time: true)
      else
        # date-span and plain strings map to String.
        Resolved.new("String")
      end
    when "integer"
      h["format"]? == "int64" ? Resolved.new("Int64") : Resolved.new("Int32")
    when "number"
      Resolved.new("Float64")
    when "boolean"
      Resolved.new("Bool")
    else
      # No type and no $ref -> free-form JSON value.
      Resolved.new("JSON::Any")
    end
  end

  def self.ref_type(schema : Schema, ref : String) : String
    name = ref.split('/').last
    schema.enum?(name) ? "Sonarr::#{name}" : "Sonarr::Model::#{name}"
  end

  def self.hash_type(schema : Schema, additional : JSON::Any?) : String
    value =
      if additional && (ah = additional.as_h?) && !ah.empty?
        value_expr(schema, additional)
      else
        "JSON::Any"
      end
    "Hash(String, #{value})"
  end

  # Crystal type expr for a nested value node (Hash value / Array item),
  # honoring `nullable: true` so nested nullable primitives become `T?`.
  # (Property-level nullability only masks this for top-level properties.)
  def self.value_expr(schema : Schema, node : JSON::Any) : String
    expr = resolve(schema, node).expr
    if (h = node.as_h?) && h["nullable"]? == JSON::Any.new(true)
      "#{expr}?"
    else
      expr
    end
  end

  # ---- emitters -------------------------------------------------------------

  def self.emit_model(schema : Schema, name : String) : String
    node = schema.objects[name].as_h
    properties = node["properties"]?.try(&.as_h) || {} of String => JSON::Any

    String.build do |io|
      io << HEADER << "\n\n"
      io << "class Sonarr::Model::#{name} < Sonarr::Model\n"
      properties.each do |key, prop|
        io << "\n"
        emit_property(schema, io, key, prop)
      end
      io << "end\n"
    end
  end

  def self.emit_property(schema : Schema, io : IO, key : String, prop : JSON::Any) : Nil
    resolved = resolve(schema, prop)
    prop_name = property_name(key)

    field = String.build do |builder|
      builder << %(key: "#{key}", emit_null: true)
      builder << ", converter: Sonarr::TimeConverter" if resolved.time
    end

    io << "  @[JSON::Field(#{field})]\n"
    if resolved.array
      # Every schema property is optional; arrays default to empty so that
      # minimal JSON never raises.
      item = resolved.expr.lchop("Array(").rchop(")")
      io << "  property #{prop_name} = [] of #{item}\n"
    else
      io << "  property #{prop_name} : #{resolved.expr}?\n"
    end
  end

  def self.emit_enums(schema : Schema) : String
    String.build do |io|
      io << HEADER << "\n\n"
      io << "require \"./support\"\n\n"
      io << "module Sonarr\n"
      schema.enums.keys.sort!.each_with_index do |name, index|
        io << "\n" if index > 0
        emit_enum(io, name, schema.enums[name])
      end
      io << "end\n"
    end
  end

  def self.emit_enum(io : IO, name : String, node : JSON::Any) : Nil
    values = node["enum"].as_a.map(&.as_s)
    io << "  def_string_enum #{name}, {\n"
    values.each do |value|
      io << "    #{member_name(value)}: #{value.inspect},\n"
    end
    io << "  }\n"
  end

  # ---- driver ---------------------------------------------------------------

  def self.run
    schema = Schema.new(SCHEMA_PATH)
    FileUtils.mkdir_p(MODEL_DIR)

    expected = Set(String).new

    schema.objects.keys.sort!.each do |name|
      file = "#{snake_case(name)}.cr"
      expected << file
      File.write(MODEL_DIR / file, emit_model(schema, name))
    end

    # Remove stale hand-written / superseded model files.
    Dir.glob(MODEL_DIR / "*.cr").each do |path|
      base = File.basename(path)
      File.delete(path) unless expected.includes?(base)
    end

    File.write(ENUMS_PATH, emit_enums(schema))

    format!(MODEL_DIR.to_s, ENUMS_PATH.to_s)

    puts "Generated #{schema.objects.size} models and #{schema.enums.size} enums."
  end

  def self.format!(*paths) : Nil
    status = Process.run("crystal", ["tool", "format", *paths],
      output: Process::Redirect::Inherit, error: Process::Redirect::Inherit)
    raise "crystal tool format failed" unless status.success?
  end
end

Generator.run
