# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

require "./support"

module Sonarr
  def_string_enum ApplyTags, {
    Add:     "add",
    Remove:  "remove",
    Replace: "replace",
  }

  def_string_enum AuthenticationRequiredType, {
    Enabled:                   "enabled",
    DisabledForLocalAddresses: "disabledForLocalAddresses",
  }

  def_string_enum AuthenticationType, {
    None:     "none",
    Basic:    "basic",
    Forms:    "forms",
    External: "external",
  }

  def_string_enum BackupType, {
    Scheduled: "scheduled",
    Manual:    "manual",
    Update:    "update",
  }

  def_string_enum CertificateValidationType, {
    Enabled:                   "enabled",
    DisabledForLocalAddresses: "disabledForLocalAddresses",
    Disabled:                  "disabled",
  }

  def_string_enum CommandPriority, {
    Normal: "normal",
    High:   "high",
    Low:    "low",
  }

  def_string_enum CommandResult, {
    Unknown:      "unknown",
    Successful:   "successful",
    Unsuccessful: "unsuccessful",
  }

  def_string_enum CommandStatus, {
    Queued:    "queued",
    Started:   "started",
    Completed: "completed",
    Failed:    "failed",
    Aborted:   "aborted",
    Cancelled: "cancelled",
    Orphaned:  "orphaned",
  }

  def_string_enum CommandTrigger, {
    Unspecified: "unspecified",
    Manual:      "manual",
    Scheduled:   "scheduled",
  }

  def_string_enum DatabaseType, {
    SqLite:     "sqLite",
    PostgreSQL: "postgreSQL",
  }

  def_string_enum DownloadProtocol, {
    Unknown: "unknown",
    Usenet:  "usenet",
    Torrent: "torrent",
  }

  def_string_enum EpisodeHistoryEventType, {
    Unknown:                "unknown",
    Grabbed:                "grabbed",
    SeriesFolderImported:   "seriesFolderImported",
    DownloadFolderImported: "downloadFolderImported",
    DownloadFailed:         "downloadFailed",
    EpisodeFileDeleted:     "episodeFileDeleted",
    EpisodeFileRenamed:     "episodeFileRenamed",
    DownloadIgnored:        "downloadIgnored",
  }

  def_string_enum EpisodeTitleRequiredType, {
    Always:             "always",
    BulkSeasonReleases: "bulkSeasonReleases",
    Never:              "never",
  }

  def_string_enum FileDateType, {
    None:         "none",
    LocalAirDate: "localAirDate",
    UtcAirDate:   "utcAirDate",
  }

  def_string_enum HealthCheckResult, {
    Ok:      "ok",
    Notice:  "notice",
    Warning: "warning",
    Error:   "error",
  }

  def_string_enum ImportListType, {
    Program:  "program",
    Plex:     "plex",
    Trakt:    "trakt",
    Simkl:    "simkl",
    Other:    "other",
    Advanced: "advanced",
  }

  def_string_enum ListSyncLevelType, {
    Disabled:         "disabled",
    LogOnly:          "logOnly",
    KeepAndUnmonitor: "keepAndUnmonitor",
    KeepAndTag:       "keepAndTag",
  }

  def_string_enum MediaCoverTypes, {
    Unknown:    "unknown",
    Poster:     "poster",
    Banner:     "banner",
    Fanart:     "fanart",
    Screenshot: "screenshot",
    Headshot:   "headshot",
    Clearlogo:  "clearlogo",
  }

  def_string_enum MonitorTypes, {
    Unknown:           "unknown",
    All:               "all",
    Future:            "future",
    Missing:           "missing",
    Existing:          "existing",
    FirstSeason:       "firstSeason",
    LastSeason:        "lastSeason",
    LatestSeason:      "latestSeason",
    Pilot:             "pilot",
    Recent:            "recent",
    MonitorSpecials:   "monitorSpecials",
    UnmonitorSpecials: "unmonitorSpecials",
    None:              "none",
    Skip:              "skip",
  }

  def_string_enum NewItemMonitorTypes, {
    All:  "all",
    None: "none",
  }

  def_string_enum PrivacyLevel, {
    Normal:   "normal",
    Password: "password",
    ApiKey:   "apiKey",
    UserName: "userName",
  }

  def_string_enum ProperDownloadTypes, {
    PreferAndUpgrade: "preferAndUpgrade",
    DoNotUpgrade:     "doNotUpgrade",
    DoNotPrefer:      "doNotPrefer",
  }

  def_string_enum ProviderMessageType, {
    Info:    "info",
    Warning: "warning",
    Error:   "error",
  }

  def_string_enum ProxyType, {
    Http:   "http",
    Socks4: "socks4",
    Socks5: "socks5",
  }

  def_string_enum QualitySource, {
    Unknown:       "unknown",
    Television:    "television",
    TelevisionRaw: "televisionRaw",
    Web:           "web",
    WebRip:        "webRip",
    Dvd:           "dvd",
    Bluray:        "bluray",
    BlurayRaw:     "blurayRaw",
  }

  def_string_enum QueueStatus, {
    Unknown:                   "unknown",
    Queued:                    "queued",
    Paused:                    "paused",
    Downloading:               "downloading",
    Completed:                 "completed",
    Failed:                    "failed",
    Warning:                   "warning",
    Delay:                     "delay",
    DownloadClientUnavailable: "downloadClientUnavailable",
    Fallback:                  "fallback",
  }

  def_string_enum RejectionType, {
    Permanent: "permanent",
    Temporary: "temporary",
  }

  def_string_enum ReleaseType, {
    Unknown:       "unknown",
    SingleEpisode: "singleEpisode",
    MultiEpisode:  "multiEpisode",
    SeasonPack:    "seasonPack",
  }

  def_string_enum RescanAfterRefreshType, {
    Always:      "always",
    AfterManual: "afterManual",
    Never:       "never",
  }

  def_string_enum RuntimeMode, {
    Console: "console",
    Service: "service",
    Tray:    "tray",
  }

  def_string_enum SeriesStatusType, {
    Continuing: "continuing",
    Ended:      "ended",
    Upcoming:   "upcoming",
    Deleted:    "deleted",
  }

  def_string_enum SeriesTypes, {
    Standard: "standard",
    Daily:    "daily",
    Anime:    "anime",
  }

  def_string_enum SortDirection, {
    Default:    "default",
    Ascending:  "ascending",
    Descending: "descending",
  }

  def_string_enum TrackedDownloadState, {
    Downloading:   "downloading",
    ImportBlocked: "importBlocked",
    ImportPending: "importPending",
    Importing:     "importing",
    Imported:      "imported",
    FailedPending: "failedPending",
    Failed:        "failed",
    Ignored:       "ignored",
  }

  def_string_enum TrackedDownloadStatus, {
    Ok:      "ok",
    Warning: "warning",
    Error:   "error",
  }

  def_string_enum UpdateMechanism, {
    BuiltIn:  "builtIn",
    Script:   "script",
    External: "external",
    Apt:      "apt",
    Docker:   "docker",
  }
end
